import React, { useEffect, useState } from "react";
import ExpeditionBattle from "./ExpeditionBattle.jsx";
import { ITEMS, canOpenChest, createFloor, eventAt, isEntrance, keepAfterDefeat, newVillage, rewardFor, walk } from "./core.js";

const SAVE = "ai_companion_expedition_b1";
const load = () => { try { const saved = JSON.parse(localStorage.getItem(SAVE) || "{}"); return { village: newVillage(saved.village || saved), floor: saved.floor || null, haul: saved.haul || [], command: saved.command || "attack", message: saved.message || "村で遠征準備をする。", battleId: saved.battleId || null }; } catch { return { village: newVillage(), floor: null, haul: [], command: "attack", message: "村で遠征準備をする。", battleId: null }; } };
export default function ExpeditionView() {
  const saved = useState(load)[0];
  const [village, setVillage] = useState(saved.village), [floor, setFloor] = useState(saved.floor), [battle, setBattle] = useState(() => saved.floor?.events.find(e => e.id === saved.battleId) || null), [command, setCommand] = useState(saved.command), [haul, setHaul] = useState(saved.haul), [message, setMessage] = useState(saved.message);
  useEffect(() => { localStorage.setItem(SAVE, JSON.stringify({ village, floor, haul, command, message, battleId: battle?.id || null })); }, [village, floor, haul, command, message, battle]);
  const start = () => { setFloor(createFloor(Date.now() >>> 0)); setHaul([]); setMessage("リディア「宝箱があるなら、寄り道も悪くないですね。」"); };
  const move = (dx, dy) => setFloor(f => { const next = walk(f, dx, dy); const e = eventAt(next); if (e) setBattle(e); return next; });
  useEffect(() => {
    if (!floor || battle) return;
    const dirs = { ArrowUp: [0, -1], ArrowDown: [0, 1], ArrowLeft: [-1, 0], ArrowRight: [1, 0] };
    const onKey = e => { const d = dirs[e.key]; if (d) { e.preventDefault(); move(...d); } };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [floor, battle]);
  const finishBattle = (result, party) => {
    if (result === "defeat") { const kept = keepAfterDefeat(haul, floor.seed); setVillage(v => ({ ...v, stash: [...v.stash, ...kept] })); setFloor(null); setBattle(null); setHaul([]); setMessage(`全滅。リディアが ${kept.length} 個を持ち帰った。`); return; }
    setFloor(f => ({ ...f, party, events: f.events.map(e => e.id === battle.id ? { ...e, done: true } : e) })); setMessage(battle.kind === "guardian" ? "リディア「守護者を倒しました。宝箱を開けましょう。」" : "リディア「道が開けました。」"); setBattle(null);
  };
  const openChest = () => { const item = rewardFor(floor); setHaul(h => [...h, item]); setFloor(f => ({ ...f, chest: { ...f.chest, opened: true } })); setMessage(`宝箱から「${ITEMS[item].name}」を入手。入口まで持ち帰れます。`); };
  const returnVillage = () => { setVillage(v => ({ ...v, stash: [...v.stash, ...haul], gold: v.gold + 8 })); setFloor(null); setHaul([]); setMessage("無事に村へ帰還。8Gと戦利品をスタッシュへ預けた。"); };
  const buy = id => { const cost = ITEMS[id].price; if (village.gold < cost) return setMessage("金貨が足りない。"); setVillage(v => ({ ...v, gold: v.gold - cost, stash: [...v.stash, id] })); };
  const sell = (id, index) => setVillage(v => ({ ...v, gold: v.gold + Math.ceil(ITEMS[id].price / 2), stash: v.stash.filter((_, i) => i !== index) }));
  const [owner, setOwner] = useState("hero");
  const equip = (id, index) => { const item = ITEMS[id]; if (item.slot === "consumable") return; setVillage(v => { const old = v.equipment[owner][item.slot]; return { ...v, stash: [...v.stash.filter((_, i) => i !== index), ...(old ? [old] : [])], equipment: { ...v.equipment, [owner]: { ...v.equipment[owner], [item.slot]: id } } }; }); };
  const useTonic = () => { const i = village.stash.indexOf("tonic"); if (i < 0) return false; setVillage(v => ({ ...v, stash: v.stash.filter((_, n) => n !== i) })); return true; };
  if (battle) return <ExpeditionBattle guardian={battle.kind === "guardian"} order={command} equipment={village.equipment} party={floor.party} tonics={village.stash.filter(i => i === "tonic").length} onUseTonic={useTonic} onFinish={finishBattle}/>;
  if (!floor) return <div style={S.page}><h1>燈火の村</h1><p style={S.message}>{message}</p><p>所持金 {village.gold}G / スタッシュ {village.stash.length}個</p><button style={S.primary} onClick={start}>地下1階へ遠征</button><section style={S.box}><b>装備</b>{[["hero","あなた"],["mage","リディア"]].map(([id,name]) => <div key={id}><b>{name}</b>{["weapon","armor","charm"].map(s => <span key={s} style={S.tag}>{s}: {village.equipment[id][s] ? ITEMS[village.equipment[id][s]].name : "なし"}</span>)}</div>)}</section><section style={S.box}><b>スタッシュ（装備先を選んでから装備）</b><div><button style={{...S.btn,...(owner === "hero" ? S.selected : {})}} onClick={() => setOwner("hero")}>あなたへ</button><button style={{...S.btn,...(owner === "mage" ? S.selected : {})}} onClick={() => setOwner("mage")}>リディアへ</button></div>{village.stash.length === 0 ? <p>空です。</p> : village.stash.map((id,i) => <div key={i} style={S.item}>{ITEMS[id].name} <button style={S.btn} onClick={() => equip(id,i)}>装備</button><button style={S.btn} onClick={() => sell(id,i)}>売る +{Math.ceil(ITEMS[id].price/2)}G</button></div>)}</section><section style={S.box}><b>固定ショップ</b><div>{["tonic","sword","mail","charm"].map(id => <button key={id} style={S.btn} onClick={() => buy(id)}>{ITEMS[id].name} {ITEMS[id].price}G</button>)}</div></section></div>;
  const e = eventAt(floor); const chest = canOpenChest(floor);
  return <div style={S.page}><header style={S.header}><b>地下1階 / seed {floor.seed}</b><span>戦利品: {haul.map(i => ITEMS[i].name).join("、") || "なし"}</span><button style={S.btn} disabled={!isEntrance(floor)} onClick={returnVillage}>入口から帰還</button></header><p style={S.message}>{message}</p><div style={S.layout}><div style={{...S.map, gridTemplateColumns:`repeat(${floor.w}, 16px)`}}>{floor.tiles.flatMap((row,y) => row.map((tile,x) => { const visible = floor.explored.includes(`${x},${y}`); const here = floor.player.x === x && floor.player.y === y; const mark = here ? "●" : (visible && x === floor.entrance.x && y === floor.entrance.y ? "△" : (visible && floor.chest.x === x && floor.chest.y === y && !floor.chest.opened ? "□" : tile)); return <span key={`${x}-${y}`} style={{...S.cell, opacity: visible || here ? 1 : .24, color: mark === "#" ? "#364050" : mark === "●" ? "#f2df7e" : "#93a4be"}}>{mark}</span>; }))}</div><aside style={S.side}><b>リディアへの指示</b>{[["attack","攻撃"],["guard","護衛"],["retreat","退却"]].map(([id,label]) => <button key={id} style={{...S.btn,...(command===id?S.selected:{})}} onClick={() => setCommand(id)}>{label}</button>)}<p>移動は矢印キーまたは下のボタンです。敵の部屋へ入ると戦闘になります。</p>{e && <button style={S.primary} onClick={() => setBattle(e)}>戦闘を開始</button>}{chest && <button style={S.primary} onClick={openChest}>宝箱を開ける</button>}</aside></div><div style={S.move}><button style={S.btn} onClick={() => move(0,-1)}>↑</button><button style={S.btn} onClick={() => move(-1,0)}>←</button><button style={S.btn} onClick={() => move(0,1)}>↓</button><button style={S.btn} onClick={() => move(1,0)}>→</button></div></div>;
}
const S={page:{minHeight:"100vh",boxSizing:"border-box",padding:"24px",background:"#161a22",color:"#e6e8ee",font:"14px/1.6 system-ui"},header:{display:"flex",gap:16,alignItems:"center",flexWrap:"wrap"},message:{color:"#d8c98c",maxWidth:620},box:{background:"#20242e",border:"1px solid #3c4354",padding:12,borderRadius:8,maxWidth:620,marginTop:12},tag:{display:"inline-block",margin:"8px 12px 0 0"},item:{padding:"5px 0"},btn:{margin:"4px",background:"#2b303c",color:"#e6e8ee",border:"1px solid #4a5366",borderRadius:5,padding:"5px 9px"},primary:{margin:"6px 0",background:"#3d7fb5",color:"#fff",border:0,borderRadius:6,padding:"8px 12px"},layout:{display:"flex",gap:24,alignItems:"start"},map:{display:"grid",background:"#0f1218",padding:10,border:"1px solid #3c4354"},cell:{height:16,width:16,textAlign:"center",fontFamily:"monospace",fontSize:14},side:{maxWidth:260},selected:{background:"#3d7fb5"},move:{marginTop:12}};
