const fs=require('node:fs'),vm=require('node:vm');
const script=fs.readFileSync(__dirname+'/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const elements={};const element=()=>({innerHTML:'',style:{},classList:{toggle(){}},querySelectorAll(){return []},querySelector(){return element()},open:false,close(){this.open=false;}});
const context=vm.createContext({document:{getElementById(id){return elements[id]??=element();}},crypto:require('node:crypto').webcrypto});
vm.runInContext(script.split("$('chat').onsubmit")[0],context);
vm.runInContext(`(async()=>{
 let count=0;const ok=(v,m)=>{count++;if(!v)throw Error(m);},rejects=fn=>{try{fn();return false;}catch{return true;}};
 const realRender=render;render=()=>{};say=(who,text,kind='')=>chat.push({who,text,kind});
 function fixture(){state=initial();state.lit=true;state.everLit=true;actionHistory=[];chat=[];explorationOffers={};announcedPoints=new Set();}
 fixture();const job=(id,action,quote='調べて')=>({id,action,quote}),intent=(jobs,kind='request')=>({jobs,kind,clarify:''});
 ok(validateExplorationIntent(intent([job('brom','inspect_cart')]),'brom','台車を調べて').jobs.length===1,'明示した調査を受理できない');
 ok(rejects(()=>validateExplorationIntent(intent([job('gareth','inspect_cart')]),'brom','調べて')),'指定外の仲間を実行');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart','偽の引用')]),'brom','調べて')),'未発言の依頼を受理');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart'),job('brom','inspect_rails')]),'all','調べて')),'同じ本人に2行動');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','smash')]),'brom','調べて')),'現場にない仕掛けを実行');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart')],'conversation'),'brom','調べて')),'相談だけで実行');
 explorationOffers.brom={room:'entry',action:'inspect_cart'};
 ok(validateExplorationIntent(intent([job('brom','inspect_cart','うん')],'approval'),'brom','うん、お願い').jobs[0].action==='inspect_cart','短い了承で提案を受理できない');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_rails','うん')],'approval'),'brom','うん')),'別の対象へ了承を流用');
 explorationOffers.gareth={room:'entry',action:'inspect_rails'};
 ok(validateExplorationIntent(intent([job('brom','inspect_cart','うん')],'approval'),'all','うん').clarify,'複数提案で勝手に選ぶ');
 state.room='hall';ok(Object.keys(currentOffers()).length===0,'別シーンの提案を流用');fixture();
 let calls=0;ask=async()=>{calls++;throw Error('結果質問に呼ばれない');};ok((await explorationIntent('何か見つかった？','brom')).jobs.length===0&&calls===0,'結果質問で調査を開始');
 ok((await explorationIntent('次はどうする？文字を解読できるなら提案して','lydia')).jobs.length===0&&calls===0,'提案の依頼で調査を開始');
 state.phase='battle';ok((await explorationIntent('台車を調べて','brom')).jobs.length===0,'戦闘で探索を開始');fixture();
 ask=async()=>{generation++;return JSON.stringify(intent([job('brom','inspect_cart')]));};ok((await explorationIntent('調べて','brom')).jobs.length===0,'古い応答を受理');
 ok(!spokenOffer('inspect_cart','レールを調べよう')&&!spokenOffer('inspect_cart','台車に工具があった')&&spokenOffer('inspect_cart','台車を調べようか？'),'口にしていない提案を記憶');
 fixture();const p=PEOPLE[1];
 apply('brom','inspect_rails');ok(conversationProgress().find(t=>t.target==='rails').status==='未共有','非公開の調査済み状態を仲間へ開示');fixture();state.knowledge.brom.push('未共有の秘密');
 explorationOffers.brom={room:'entry',action:'inspect_cart'};$('sheet').open=true;
 acceptAI(p,{speech:'捏造した報告',action:'inspect_cart',requested:'inspect_cart',profileClaims:[],share:false,shareClues:[]},false);
 ok(state.seen.brom.includes('cart')&&actionHistory.length===1,'調査を実行していない');
 ok(actionHistory[0].initiator==='ines','依頼元が本人になった');
 ok(chat.some(c=>c.text.includes('鉄の工具'))&&!chat.some(c=>c.text.includes('捏造した報告')),'実際の結果以外を報告');
 ok(actionsFor('ines').includes('take')&&chat.some(c=>c.text.includes('工具を拾って')),'仲間の報告からイネスへの依頼と拾う行動につながらない');
 ok(state.shared.some(x=>x.includes('鉄の工具'))&&!state.shared.some(x=>x.includes('未共有の秘密')),'実結果の共有か情報保護が不正');
 ok(conversationProgress().find(t=>t.target==='cart').status==='調査結果共有済み','公開の調査結果が進捗にない');
 ok(!explorationOffers.brom&&!$('sheet').open,'実行後に提案とシートが残った');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart')]),'brom','調べて')),'調査済みを二重実行');
 ask=async()=>JSON.stringify(intent([job('brom','inspect_cart')]));ok((await explorationIntent('調べて','brom')).jobs.length===0&&actionHistory.length===1,'調査済みへの依頼で会話が止まるか二重実行');
 apply('ines','take');ok(conversationProgress().find(t=>t.target==='cart').status==='工具取得済み'&&!inspectText('brom','cart',state).includes('残っている'),'取得後の台車に工具が残っている');
 let progressInput;ask=async(system,payload)=>{progressInput=payload;return JSON.stringify({speech:'共有の工具として使わせてもらうよ',action:'wait',share:false});};await aiPlayer(p);
 ok(!progressInput.humanOptions.inspect_cart&&progressInput.humanOptions.inspect_rails,'取得済みを再依頼候補に含めるか未調査を消す');
 ok(progressInput.inventory.scope==='individual'&&progressInput.inventory.others.some(i=>i.name==='鉄の工具'&&i.holder==='ines')&&!progressInput.inventory.items.some(i=>i.id==='ironbar'),'個別の所有者を渡していない');
 recipient='all';chat=[];const requests=[];ask=async(system,payload)=>{requests.push(payload);return JSON.stringify({speech:'工具は仲間と使えるね',action:'wait',share:false});};for(const person of PEOPLE.slice(1))await aiPlayer(person);
 ok(requests.filter(r=>r.mayRequestHuman).length===1&&requests.filter(r=>Object.keys(r.humanOptions).length).length===1,'全員が同じターンに人間への依頼を出せる');
 chat.push({kind:'you',text:'覚えておこう'});await aiPlayer(PEOPLE[2]);ok(requests.at(-1).mayRequestHuman,'依頼できる仲間が交代しない');
 acceptAI(PEOPLE[2],{speech:'レールを調べてみようか？',action:'wait',proposal:'inspect_rails',profileClaims:[],share:false,shareClues:[]},false);
 ok(currentOffers().gareth.action==='inspect_rails'&&!state.seen.gareth,'提案だけで調査を実行');
 fixture();state.discovery.etching=true;learnClue('lydia','etching');
 let aiInput;ask=async(system,payload)=>{aiInput=payload;return JSON.stringify({speech:'もう解読したわ。',action:'decode',share:true,proposal:'decode',shareClues:['etching']});};
 const alternate=await aiPlayer(PEOPLE[3],false,'inspect_etching');
 ok(Object.keys(aiInput.allowed).join()==='inspect_etching','依頼中に別の実行候補を渡す');
 ok(alternate.action==='wait'&&alternate.proposal==='decode'&&alternate.speech.includes('してよいですか'),'観察と解読の違いで会話が停止');
 ok(!alternate.share&&alternate.shareClues.length===0&&!alternate.speech.includes('もう解読した'),'保留時に未実行の発見を報告');
 acceptAI(PEOPLE[3],alternate,false);ok(actionHistory.length===0&&currentOffers().lydia.action==='decode','確認だけで解読を実行');
 ask=async()=>JSON.stringify(intent([job('lydia','decode','うん')],'approval'));ok((await explorationIntent('うん、お願い','lydia')).jobs[0].action==='decode','解読提案を了承できない');
 ask=async()=>JSON.stringify({speech:'台車を調べるわ',action:'inspect_cart',share:false});let mismatch=false;try{await aiPlayer(PEOPLE[3],false,'inspect_etching');}catch{mismatch=true;}ok(mismatch,'別の対象への依頼差し替えを許可');
 ask=async()=>JSON.stringify({speech:'存在しない行動',action:'invented',share:false});let malformed=false;try{await aiPlayer(PEOPLE[3],false,'inspect_etching');}catch{malformed=true;}ok(malformed,'不正な行動を確認に流用');
 acceptAI(PEOPLE[3],{speech:'解読するわ',action:'decode',requested:'decode',profileClaims:[],share:false,shareClues:[]},false);
 ok(state.discovery.shared.includes('darkness')&&chat.some(c=>c.text.includes('灯を伏せよ')),'解読結果が共有されない');
 ok(conversationProgress().find(t=>t.target==='etching').status==='解読済み','解読の公開結果が進捗にない');
 fixture();announceVisiblePoints();const n=chat.length;announceVisiblePoints();ok(n===1&&chat.length===1,'見える候補を繰り返し報告');
 ok(chat[0].text.includes('台車')&&!chat[0].text.includes('工具')&&!chat[0].text.includes('刻み'),'未調査の結果や隠し対象を開示');
 fixture();state.lit=false;announceVisiblePoints();ok(chat.length===0,'暗闇で見えていない対象を開示');
 fixture();state.discovery.cache=true;learnClue('gareth','cache_lock');ok(rejects(()=>validateExplorationIntent(intent([job('gareth','open_cache')],'survey'),'gareth','調べて')),'分担調査で解錠を実行');
 let dice=null;openDice=(mode,prepared)=>dice={mode,prepared};checkedReply=async()=>{throw Error('解錠画面後に会話を続けない');};busy=true;
 await companions(false,'gareth',[job('gareth','open_cache')]);ok(dice?.mode==='cache'&&dice.prepared&&!state.discovery.opened,'会話から既存判定へ接続できない');busy=false;
 fixture();positionGM=()=>{};renderPlacement=()=>{};placeTargetLabels=()=>{};updateRecipients=()=>{};redrawEffects=()=>{};refreshOpenSheet=()=>{};target='cart';realRender();
 ok(!$('actions').innerHTML.includes('data-request')&&$('actions').innerHTML.includes('data-act="inspect_cart"'),'調査ポイントに他者の選択肢が残る');
 return count;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 明示依頼と短い了承 / 曖昧な提案の確認 / 指定相手・発言根拠 / 調査と実結果の共有 / 個人情報の保護 / 解読 / 候補の自発共有 / 二重実行・古い応答 / 会話から解錠判定 / 自分だけの選択肢')).catch(e=>{console.error(e);process.exitCode=1;});
