const fs=require('node:fs'),vm=require('node:vm');
const loadPrototype=require('./load-prototype.cjs').load;
const elements={};const element=()=>({innerHTML:'',style:{removeProperty(){}},classList:{toggle(){},contains(){return false}},append(){},insertBefore(){},querySelectorAll(){return []},querySelector(){return element()},open:false,close(){this.open=false;}});
const context=vm.createContext({document:{getElementById(id){return elements[id]??=element();},querySelector(){return element()}},crypto:require('node:crypto').webcrypto});
loadPrototype(context);
vm.runInContext(`(async()=>{
 let count=0;const ok=(v,m)=>{count++;if(!v)throw Error(m);},rejects=fn=>{try{fn();return false;}catch{return true;}};
 const realRender=render;render=()=>{};say=(who,text,kind='')=>chat.push({who,text,kind});
 function fixture(){humanRequests=[];state=initial();state.lit=true;state.everLit=true;actionHistory=[];chat=[];explorationOffers={};announcedPoints=new Set();}
 fixture();state.room='hall';reportInvestigation(PEOPLE[0],'inspect',apply('ines','inspect'));revealProfile('lydia',[{key:'item2'}]);chat=[];
 ok(cooperationConversation('ブロムが支え、ガレスが隙間から留め具を外してみて','all'),'実行不能の複数人への分担が相談へ流れる');
 ok(chat.some(c=>c.kind==='gm'&&c.text.includes('支えられません')&&c.text.includes('イネスの能力'))&&!state.supported&&!state.opened,'水圧と担当の不備を訂正しないか勝手に実行');
 ok(chat.every(c=>!c.text.includes('排水室'))&&currentMapOffer()?.holder==='lydia','未知の地名を明かすか地図の相談へつながらない');
 const blockedBefore=JSON.stringify(state);
 ok(cooperationConversation('水の圧力で動かないね','all')&&JSON.stringify(state)===blockedBefore,'行き詰まりの報告から状態を変更');
 const blockedInput=dialogueInput(PEOPLE[2],false,null,null);
 ok(blockedInput.blockedActions.some(b=>b.action==='support')&&blockedInput.blockedActions.some(b=>b.actor==='gareth'&&b.action==='crawl'),'仲間の判断へ実行不能の理由を渡さない');
 state.drained=true;ok(!dialogueInput(PEOPLE[1],false,null,null).blockedActions.some(b=>b.action==='support'),'排水後も水圧の制約を残す');
 fixture();state.room='hall';ok(!dialogueInput(PEOPLE[2],false,null,null).blockedActions.length,'未調査の仕掛けの条件を先に暴露');
 fixture();state.room='hall';
 const lockBefore=JSON.stringify(state);
 ask=async()=>JSON.stringify({speech:'水の圧力か。ブロムが支えてくれるなら、俺の出番だな。鍵を外してみるよ。',action:'unlock',share:false,proposal:'unlock',shareClues:[]});
 const lockOffer=await aiPlayer(PEOPLE[2]);
 ok(lockOffer.action==='wait'&&lockOffer.proposal==='unlock','相談中の解錠指定で会話が止まる');
 acceptAI(PEOPLE[2],lockOffer,false);
 ok(state.locked&&actionHistory.length===0&&currentOffers().gareth?.action==='unlock','了承前に解錠するか申し出を失う');
 ok(JSON.stringify(state)===lockBefore,'申し出への補正でゲーム状態を変更');
 ok(!spokenOffer('unlock','鍵は外さない。')&&!spokenOffer('unlock','鍵は外せない。'),'否定を解錠の申し出にする');
 ask=async()=>JSON.stringify({speech:'俺が火球を使う',action:'fire',share:false});
 let invalidOffer=false;try{await aiPlayer(PEOPLE[2]);}catch{invalidOffer=true;}ok(invalidOffer,'候補外の行動を補正して受理');
 fixture();const job=(id,action,quote='調べて')=>({id,action,quote}),intent=(jobs,kind='request')=>({jobs,kind,clarify:''});
 ok(validateExplorationIntent(intent([job('brom','inspect_cart')]),'brom','台車を調べて').jobs.length===1,'明示した調査を受理できない');
 ok(rejects(()=>validateExplorationIntent(intent([job('gareth','inspect_cart')]),'brom','調べて')),'指定外の仲間を実行');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart','偽の引用')]),'brom','調べて')),'未発言の依頼を受理');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart'),job('brom','inspect_rails')]),'all','調べて')),'同じ本人に2行動');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','smash')]),'brom','調べて')),'現場にない仕掛けを実行');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart')],'conversation'),'brom','調べて')),'相談だけで実行');
 explorationOffers.brom={room:'entry',action:'inspect_cart'};
 ok(validateExplorationIntent(intent([job('brom','inspect_cart','うん')],'approval'),'brom','うん、お願い').jobs[0].action==='inspect_cart','短い了承で提案を受理できない');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_rails','うん')],'approval'),'brom','うん')),'別の対象へ了承を流用');
 explorationOffers.gareth={room:'entry',action:'inspect_rails'};
 ok(validateExplorationIntent(intent([job('brom','inspect_cart','うん')],'approval'),'all','うん').clarify,'複数提案で勝手に選ぶ');
 state.room='hall';ok(Object.keys(currentOffers()).length===0,'別シーンの提案を流用');fixture();
 let calls=0;ask=async()=>{calls++;throw Error('結果質問に呼ばれない');};ok((await explorationIntent('何か見つかった？','brom')).jobs.length===0&&calls===0,'結果質問で調査を開始');
 ok((await explorationIntent('次はどうする？文字を解読できるなら提案して','lydia')).jobs.length===0&&calls===0,'提案の依頼で調査を開始');
 state.phase='battle';ok((await explorationIntent('台車を調べて','brom')).jobs.length===0,'戦闘で探索を開始');fixture();
 state.room='drain';ask=async()=>JSON.stringify(intent([job('brom','inspect_wheel','操作輪を調べる')]));
 const adjusted=await explorationIntent('操作輪を調べて','brom');ok(adjusted.jobs[0]?.action==='inspect_wheel'&&adjusted.jobs[0]?.quote==='操作輪を調べて','引用の言い換えで明示依頼が止まる');
 ask=async()=>JSON.stringify(intent([job('brom','inspect_wheel','操作輪を調べる')],'conversation'));
 ok((await explorationIntent('力仕事は得意？','brom')).jobs.length===0,'質問に混ざった行動を実行');
 ask=async()=>JSON.stringify(intent([job('brom','inspect_water','水溜まりを調べる')]));
 ok((await explorationIntent('操作輪を調べて','brom')).jobs.length===0,'引用補正で違う対象を調査');
 ask=async()=>JSON.stringify(intent([job('gareth','inspect_wheel','操作輪を調べる')]));
 ok((await explorationIntent('操作輪を調べて','brom')).jobs.length===0,'引用補正で指定外の仲間へ依頼');
 ask=async()=>JSON.stringify(intent([job('brom','inspect_wheel','操作輪を調べる')]));
 ok((await explorationIntent('操作輪は調べてはいけない','brom')).jobs.length===0,'否定した調査を補正して実行');
 ok((await explorationIntent('操作輪を調べたらどうなる？','brom')).jobs.length===0,'仮定の質問を補正して実行');
 ask=async()=>'{broken';ok((await explorationIntent('力仕事は得意？','brom')).jobs.length===0,'JSON形式の失敗で会話が停止');
 ask=async()=>JSON.stringify(intent([null]));ok((await explorationIntent('力仕事は得意？','brom')).jobs.length===0,'空の行動候補で会話が停止');
 ask=async()=>JSON.stringify(intent([job('brom','invented','操作輪を調べて')]));ok((await explorationIntent('操作輪を調べて','brom')).jobs.length===0,'存在しない行動を実行');
 fixture();
 ask=async()=>{generation++;return JSON.stringify(intent([job('brom','inspect_cart')]));};ok((await explorationIntent('調べて','brom')).jobs.length===0,'古い応答を受理');
 ok(!spokenOffer('inspect_cart','レールを調べよう')&&!spokenOffer('inspect_cart','台車に工具があった')&&spokenOffer('inspect_cart','台車を調べようか？'),'口にしていない提案を記憶');
 fixture();const p=PEOPLE[1];
 apply('brom','inspect_rails');ok(conversationProgress().find(t=>t.target==='rails').status==='未共有','非公開の調査済み状態を仲間へ開示');fixture();state.knowledge.brom.push('未共有の秘密');
 explorationOffers.brom={room:'entry',action:'inspect_cart'};$('sheet').open=true;
 acceptAI(p,{speech:'捏造した報告',action:'inspect_cart',requested:'inspect_cart',profileClaims:[],share:false,shareClues:[]},false);
 ok(state.seen.brom.includes('cart')&&actionHistory.length===1,'調査を実行していない');
 ok(actionHistory[0].initiator==='ines','依頼元が本人になった');
 ok(chat.some(c=>c.text.includes('鉄の工具'))&&!chat.some(c=>c.text.includes('捏造した報告')),'実際の結果以外を報告');
 ok(actionsFor('ines').includes('take')&&chat.some(c=>c.text.includes('工具を拾って')),'仲間の報告からイネスへの依頼と拾う行動につながらない');
 ok(state.shared.some(x=>x.includes('鉄の工具'))&&!state.shared.some(x=>x.includes('未共有の秘密')),'実結果の共有か情報保護が不正');
 ok(conversationProgress().find(t=>t.target==='cart').status==='調査結果共有済み','公開の調査結果が進捗にない');
 ok(!explorationOffers.brom&&!$('sheet').open,'実行後に提案とシートが残った');
 ok(rejects(()=>validateExplorationIntent(intent([job('brom','inspect_cart')]),'brom','調べて')),'調査済みを二重実行');
 ask=async()=>JSON.stringify(intent([job('brom','inspect_cart')]));ok((await explorationIntent('調べて','brom')).jobs.length===0&&actionHistory.length===1,'調査済みへの依頼で会話が止まるか二重実行');
 apply('ines','take');ok(conversationProgress().find(t=>t.target==='cart').status==='工具取得済み'&&!inspectText('brom','cart',state).includes('残っている'),'取得後の台車に工具が残っている');
 let progressInput;ask=async(system,payload)=>{progressInput=payload;return JSON.stringify({speech:'共有の工具として使わせてもらうよ',action:'wait',share:false});};await aiPlayer(p);
 ok(!progressInput.humanOptions.inspect_cart&&progressInput.humanOptions.inspect_rails,'取得済みを再依頼候補に含めるか未調査を消す');
 ok(progressInput.inventory.scope==='individual'&&progressInput.inventory.others.some(i=>i.name==='鉄の工具'&&i.holder==='ines')&&!progressInput.inventory.items.some(i=>i.id==='ironbar'),'個別の所有者を渡していない');
 recipient='all';chat=[];const requests=[];ask=async(system,payload)=>{requests.push(payload);return JSON.stringify({speech:'工具は仲間と使えるね',action:'wait',share:false});};for(const person of PEOPLE.slice(1))await aiPlayer(person);
 ok(requests.filter(r=>r.mayRequestHuman).length===1&&requests.filter(r=>Object.keys(r.humanOptions).length).length===1,'全員が同じターンに人間への依頼を出せる');
 chat.push({kind:'you',text:'覚えておこう'});await aiPlayer(PEOPLE[2]);ok(requests.at(-1).mayRequestHuman,'依頼できる仲間が交代しない');
 acceptAI(PEOPLE[2],{speech:'レールを調べてみようか？',action:'wait',proposal:'inspect_rails',profileClaims:[],share:false,shareClues:[]},false);
 ok(currentOffers().gareth.action==='inspect_rails'&&!state.seen.gareth,'提案だけで調査を実行');
 fixture();state.discovery.etching=true;learnClue('lydia','etching');
 let aiInput;ask=async(system,payload)=>{aiInput=payload;return JSON.stringify({speech:'もう解読したわ。',action:'decode',share:true,proposal:'decode',shareClues:['etching']});};
 const alternate=await aiPlayer(PEOPLE[3],false,'inspect_etching');
 ok(Object.keys(aiInput.allowed).join()==='inspect_etching','依頼中に別の実行候補を渡す');
 ok(alternate.action==='wait'&&alternate.proposal==='decode'&&alternate.speech.includes('してよいですか'),'観察と解読の違いで会話が停止');
 ok(!alternate.share&&alternate.shareClues.length===0&&!alternate.speech.includes('もう解読した'),'保留時に未実行の発見を報告');
 acceptAI(PEOPLE[3],alternate,false);ok(actionHistory.length===0&&currentOffers().lydia.action==='decode','確認だけで解読を実行');
 ask=async()=>JSON.stringify(intent([job('lydia','decode','うん')],'approval'));ok((await explorationIntent('うん、お願い','lydia')).jobs[0].action==='decode','解読提案を了承できない');
 ask=async()=>JSON.stringify({speech:'台車を調べるわ',action:'inspect_cart',share:false});let mismatch=false;try{await aiPlayer(PEOPLE[3],false,'inspect_etching');}catch{mismatch=true;}ok(mismatch,'別の対象への依頼差し替えを許可');
 ask=async()=>JSON.stringify({speech:'存在しない行動',action:'invented',share:false});let malformed=false;try{await aiPlayer(PEOPLE[3],false,'inspect_etching');}catch{malformed=true;}ok(malformed,'不正な行動を確認に流用');
 acceptAI(PEOPLE[3],{speech:'解読するわ',action:'decode',requested:'decode',profileClaims:[],share:false,shareClues:[]},false);
 ok(state.discovery.shared.includes('darkness')&&chat.some(c=>c.text.includes('灯を伏せよ')),'解読結果が共有されない');
 ok(conversationProgress().find(t=>t.target==='etching').status==='解読済み','解読の公開結果が進捗にない');
 fixture();announceVisiblePoints();const n=chat.length;announceVisiblePoints();ok(n===1&&chat.length===1,'見える候補を繰り返し報告');
 ok(chat[0].text.includes('台車')&&!chat[0].text.includes('工具')&&!chat[0].text.includes('刻み'),'未調査の結果や隠し対象を開示');
 fixture();state.lit=false;announceVisiblePoints();ok(chat.length===0,'暗闇で見えていない対象を開示');
 fixture();const savedSettle=settleConsent,savedChecked=checkedReply;settleConsent=async()=>{};checkedReply=async()=>{throw Error('観察に追加のAI照合をしない');};
 state.room='drain';await companions(false,'brom',[job('brom','inspect_wheel')]);
 ok(state.seen.brom.includes('wheel')&&chat.some(c=>c.text.startsWith('調べた結果：')&&c.text.includes('操作輪')),'明示した観察がその場で実行・報告されない');
 ok(actionHistory.at(-1).action==='inspect_wheel'&&actionHistory.at(-1).initiator==='ines','観察の履歴と依頼元が欠ける');
 settleConsent=savedSettle;checkedReply=savedChecked;
 fixture();chat=[{kind:'you',text:'力仕事は得意？'}];recipient='brom';state.knowledge.brom.push('未共有の調査結果');
 const focused=dialogueInput(PEOPLE[1],false,null,null);
 ok(focused.focus.type==='profile'&&focused.selfProfile.skill0&&!focused.selfProfile.skill1&&!focused.selfProfile.origin,'能力質問へ別の技能や経歴を渡す');
 ok(focused.question==='力仕事は得意？'&&focused.public.targets===undefined&&focused.knowledge.length===0&&focused.shared.length===0&&Object.keys(focused.proposalChoices).length===0&&Object.keys(focused.humanOptions).length===0,'人物質問へ探索候補・秘密・人間への依頼を渡す');
 ok(dialogueFocus(PEOPLE[3],'出身はどこ？').keys.join()==='origin'&&dialogueFocus(PEOPLE[2],'生い立ちを教えて').keys.includes('past'),'人物質問の焦点を識別できない');
 ok(dialogueFocus(PEOPLE[3],'地図を見せて').type==='navigation'&&dialogueFocus(PEOPLE[1],'操作輪を支えて').type==='conversation','実行依頼を人物質問にする');
 state.phase='battle';plan=[{id:'ines',action:'study'}];const battleInput=dialogueInput(PEOPLE[1],true,null,null);
 ok(battleInput.focus.type==='battle'&&battleInput.question.includes('戦闘行動')&&!battleInput.allowed.wait&&battleInput.progress.length===0&&Object.keys(battleInput.proposalChoices).length===0&&!battleInput.selfProfile.past&&battleInput.public.forecast,'戦闘の入力に雑談や探索候補を混ぜる');state.phase='explore';plan=[];
 state.phase='battle';chat.push({kind:'you',text:'ブロム、無理にかばわないで。攻撃と退路を相談しよう。'});ok(dialogueInput(PEOPLE[1],true,null,null).conversation.some(c=>c.text.includes('無理にかばわないで')),'戦闘の本人判断から人間の反対・相談を落とす');state.phase='explore';
 state.phase='battle';let battleCalls=0;ask=async(system,payload)=>{battleCalls++;if(battleCalls===1)return JSON.stringify({speech:'弱点を探るわ',action:'detect_weakness',share:false});ok(payload.formatCorrection.includes('fire, spark, retreat'),'候補外の選び直しに本人の候補を渡さない');return JSON.stringify({speech:'火球で攻撃するわ',action:'fire'});};
 const correctedBattle=await aiPlayer(PEOPLE[3],true);ok(battleCalls===2&&correctedBattle.action==='fire'&&correctedBattle.share===false,'候補外の戦闘行動を実行か選び直し後も停止');
 battleCalls=0;ask=async()=>{battleCalls++;return JSON.stringify({speech:'弱点を探るわ',action:'detect_weakness',share:false});};let invalidBattle=false;try{await aiPlayer(PEOPLE[3],true);}catch{invalidBattle=true;}
 ok(invalidBattle&&battleCalls===2&&actionHistory.length===0,'戦闘候補外を自動の代替行動へ変換か繰り返し過ぎる');
 battleCalls=0;ask=async()=>{battleCalls++;return battleCalls===1?'not json':JSON.stringify({speech:'盾で前衛をかばうぞ',action:'cover',share:false});};
 ok((await aiPlayer(PEOPLE[1],true)).action==='cover'&&battleCalls===2,'戦闘JSONの読み取り失敗から選び直せない');state.phase='explore';
 // 光線の予告ではかばうが効かないため候補から外し、理由を本人判断と連携確認へ渡します。選ばれても攻撃へ黙って置き換えません（2026-10-08）。
 state.phase='battle';state.round=2;const beamInput=dialogueInput(PEOPLE[1],true,null,null);ok(!beamInput.allowed.cover&&beamInput.allowed.strike&&beamInput.public.forecast==='マレンへの光線'&&beamInput.blockedActions.some(b=>b.action==='cover'&&b.reason.includes('光線')),'光線の予告でかばうが選べる、または理由が届かない');
 battleCalls=0;ask=async()=>{battleCalls++;return JSON.stringify(battleCalls===1?{speech:'マレンをかばうぞ',action:'cover',share:false}:{speech:'金槌で殴るぞ',action:'strike',share:false});};ok((await aiPlayer(PEOPLE[1],true)).action==='strike'&&battleCalls===2,'光線の予告でかばうを採用');
 battleCalls=0;ask=async()=>{battleCalls++;return JSON.stringify({speech:'マレンをかばうぞ',action:'cover',share:false});};let beamCover=false;try{await aiPlayer(PEOPLE[1],true);}catch{beamCover=true;}ok(beamCover&&battleCalls===2&&actionHistory.length===0,'効かないかばうを攻撃へ黙って置き換える');
 const savedAudit=auditProfile;auditProfile=async()=>({valid:true,claims:[]});plan=[{id:'ines',action:'study'},{id:'brom',action:'strike'},{id:'gareth',action:'stab'},{id:'lydia',action:'fire'}];let coordinationInput=null;ask=async(system,payload)=>{if(payload.self==='brom'){coordinationInput=payload;return JSON.stringify({speech:'やはりかばう',action:'cover',agrees:true});}return JSON.stringify({speech:'了解',action:payload.own.action,agrees:true});};
 let coordinationRejected=false;try{await coordinatePlan();}catch{coordinationRejected=true;}auditProfile=savedAudit;ok(coordinationRejected&&coordinationInput.blockedActions.some(b=>b.action==='cover')&&!coordinationInput.allowed.cover&&coordinationInput.rules.includes('光線はかばえない')&&!plan.some(p=>p.action==='cover')&&!planReady(),'連携確認で効かないかばうを採用');
 state.round=1;state.phase='explore';plan=[];planReview=null;
 let classificationCalls=0;ask=async()=>{classificationCalls++;return JSON.stringify({kind:'conversation',jobs:[],clarify:''});};
 ok((await explorationIntent('力仕事は得意？','brom')).jobs.length===0&&classificationCalls===0,'人物質問に不要な調査分類を呼ぶ');
 fixture();state.room='drain';acquireItem('ines','ironbar');reportInvestigation(PEOPLE[1],'inspect_wheel',apply('brom','inspect_wheel'));
 ok(!state.holding&&currentOffers().brom?.action==='hold'&&chat.some(c=>c.text.includes('その工具で')),'実調査から支援の申し出につながらないか先に実行');
 ok((await explorationIntent('うん、お願いします','brom')).jobs[0]?.action==='hold'&&classificationCalls===0,'申し出への短い了承を実行依頼へつなげない');
 ok((await explorationIntent('お願い','gareth')).jobs.length===0,'別の本人への了承で支援する');
 ok(!state.holding,'了承の分類だけで支援を実行');
 acceptAI(PEOPLE[1],{speech:'支えよう',action:'hold',requested:'hold',profileClaims:[],share:false,shareClues:[]},false);
 ok(state.holding&&actionsFor('ines').includes('pry')&&chat.at(-1).text.includes('引っ掛かりを外して'),'本人の支援から人間の実行へつながらない');
 fixture();state.room='drain';acquireItem('ines','ironbar');offerCooperation('brom','hold','俺が操作輪を支えようか？');const savedReply=checkedReply;checkedReply=async()=>{throw Error('了承済みの申し出を再度AIに質問しない');};
 await companions(false,'brom',[job('brom','hold')]);ok(state.holding&&!currentOffers().brom,'申し出の了承後に本人が支援しない');checkedReply=savedReply;
 const drained=apply('ines','pry');cooperationFollowup('ines','pry');ok(state.drained&&chat.at(-1).text.includes('もう一方の通路')&&!chat.at(-1).text.includes('石扉の広間'),'未訪問の行き先を暴露');
 fixture();state.room='drain';ok(wheelConversation('誰か操作輪の鉄片を取って').clarify.includes('先に操作輪を調べ'),'未調査の作業を先に暴露');
 reportInvestigation(PEOPLE[1],'inspect_wheel',apply('brom','inspect_wheel'));
 ok(wheelConversation('ガレス、鉄片を取って').clarify.includes('先にブロム'),'必要な支えを案内しない');apply('brom','hold');
 ok(wheelConversation('誰か鉄片を取って').clarify.includes('工具が必要'),'道具がないのに作業を開始');acquireItem('ines','ironbar');
 ok(wheelConversation('ガレス、鉄片を外して').clarify.includes('イネスが担当'),'別の仲間に細かい作業を実行させる');
 ok(wheelConversation('私が工具で鉄片を外す').selfAction==='pry'&&!state.drained,'自分の宣言を識別できないか識別だけで実行');
 for(const text of ['私が鉄片を外せる？','私が鉄片を外した','もし私が鉄片を外す','私が鉄片を外すつもり','私が鉄片を外すのはやめる','誰か鉄片を外す','私が鉄片を外すのではなく、ガレスが外す'])ok(!wheelConversation(text).selfAction,'質問・過去・仮定・予定・否定・他人の行動を実行');
 const recipientUI=updateRecipients;updateRecipients=()=>{};$('sheet').open=true;await submitMessage('私が工具で鉄片を外す','all');updateRecipients=recipientUI;ok(state.drained&&!state.holding&&actionHistory.at(-1).action==='pry'&&!$('sheet').open,'会話から本人の実作業が進まないかシートが閉じない');
 ok(wheelConversation('鉄片を取って').clarify.includes('排水済み'),'済んだ作業を再び頼む');
 fixture();state.room='drain';state.holding=true;acquireItem('ines','ironbar');state.items.ironbar.holder='brom';ok(wheelConversation('私が鉄片を外す').clarify.includes('ブロムが持っています'),'現在の所持者を見ずに工具を使う');
 state.phase='battle';ok(wheelConversation('鉄片を取って')===null,'戦闘へ探索の案内を混ぜる');fixture();ok(wheelConversation('鉄片を取って')===null&&wheelConversation('工具をブロムに渡す')===null,'別の場面・受け渡しを鉄片の作業へ取り違える');
 fixture();state.discovery.etching=true;reportInvestigation(PEOPLE[1],'inspect_etching',apply('brom','inspect_etching'));
 ok(currentOffers().lydia?.action==='decode'&&!knowsClue('lydia','darkness')&&chat.at(-1).text.includes('解読'),'共有後の解読提案か未解読の保護が不正');
 reportInvestigation(PEOPLE[3],'decode',apply('lydia','decode'));ok(state.lit&&consentCandidate('lantern',currentConsent('lantern'))===null&&chat.at(-1).text.includes('ランタンを消して'),'解読だけで消灯したか次の提案がない');
 fixture();state.discovery.etching=true;learnClue('lydia','etching');let lanternSettles=0;const savedLantern=settleConsent;settleConsent=async()=>{lanternSettles++;};
 await companions(false,'lydia',[job('lydia','decode')]);ok(lanternSettles===0&&state.lit&&currentConsent('lantern')?.voices['lydia:douse'],'解読への了承を、その後に提案した消灯へ流用');settleConsent=savedLantern;
 fixture();state.room='hall';state.drained=true;state.observedDrain=true;reportInvestigation(PEOPLE[2],'inspect',apply('gareth','inspect'));
 ok(!inspectText('gareth','door',state).includes('圧力は残る')&&!inspectText('ines','door',state).includes('かかっている')&&!inspectText('lydia','door',state).includes('染み出して'),'排水済みなのに調査結果へ水圧を残す');
 ok(currentOffers().gareth?.action==='unlock'&&state.locked,'調査後に本人へ解錠を申し出ないか先に実行');
 acceptAI(PEOPLE[2],{speech:'鍵を外すよ',action:'unlock',requested:'unlock',profileClaims:[],share:false,shareClues:[]},false);
 ok(!state.locked&&!state.supported&&currentOffers().brom?.action==='support','解錠後にブロムの支援提案へつながらない');
 acceptAI(PEOPLE[1],{speech:'支えるよ',action:'support',requested:'support',profileClaims:[],share:false,shareClues:[]},false);
 ok(state.supported&&!state.opened&&chat.at(-1).text.includes('留め具'),'支援後に自分の行動が分からないか扉を先に開けた');
 fixture();state.drained=true;ok(move('hall').includes('広間に入ると'),'初訪問を再訪と報告する');fixture();state.visited.push('hall');state.drained=true;ok(move('hall').includes('広間へ戻ると'),'再訪の変化を初訪問と報告する');
 fixture();explorationOffers.brom={room:'entry',action:'inspect_cart'};explorationOffers.gareth={room:'entry',action:'inspect_rails'};
 ok((await explorationIntent('お願い','all')).clarify,'複数人の申し出を了承だけで勝手に選ぶ');
 fixture();state.discovery.cache=true;learnClue('gareth','cache_lock');ok(rejects(()=>validateExplorationIntent(intent([job('gareth','open_cache')],'survey'),'gareth','調べて')),'分担調査で解錠を実行');
 let dice=null;openDice=(mode,prepared)=>dice={mode,prepared};checkedReply=async()=>{throw Error('解錠画面後に会話を続けない');};busy=true;
 await companions(false,'gareth',[job('gareth','open_cache')]);ok(dice?.mode==='cache'&&dice.prepared&&!state.discovery.opened,'会話から既存判定へ接続できない');busy=false;
 fixture();state.room='drain';
 ok(cooperationAdvice('gareth').action==='inspect_wheel'&&!state.holding,'未共有の操作輪から先に作業を暴露');
 ok(cooperationConversation('次は何をすればいい？','gareth')&&currentOffers().gareth?.action==='inspect_wheel'&&actionHistory.length===0,'次の相談を実行にせず調査の申し出にする');
 fixture();state.room='drain';reportInvestigation(PEOPLE[2],'inspect_wheel',apply('gareth','inspect_wheel'));
 const historyBefore=actionHistory.length;
 ok(cooperationConversation('操作輪の鉄片を外して','brom')&&chat.some(c=>c.who==='ブロム（AI）'&&c.text.includes('イネスが得意'))&&currentOffers().brom?.action==='hold'&&!state.holding&&actionHistory.length===historyBefore,'不得意な依頼を理由・本人の協力に返せないか先に支える');
 apply('brom','hold');chat=[];cooperationConversation('次はどうする？','lydia');
 ok(chat.at(-1).text.includes('工具を探して')&&!chat.some(c=>c.text.includes('台車')),'道具未発見で場所を暴露するか次の準備が分からない');
 acquireItem('ines','ironbar');state.items.ironbar.holder='gareth';chat=[];cooperationConversation('次は何をすればいい？','all');
 ok(chat.at(-1).text.includes('ガレス')&&chat.at(-1).text.includes('借り')&&!state.drained,'工具の個別所持を無視するか相談で排水');
 state.items.ironbar.holder='ines';ok(cooperationAdvice().action==='pry','支え・工具がそろった後に人間へ作業を頼まない');
 apply('ines','pry');chat=[];cooperationConversation('操作輪の鉄片を外して','lydia');
 ok(chat[0].text.includes('もう済んで')&&chat.at(-1).text.includes('入口')&&!chat.some(c=>c.text.includes('石扉の広間')),'排水済みを繰り返すか未訪問地名を暴露');
 fixture();state.discovery.etching=true;learnClue('ines','etching');
 ok(cooperationAdvice().action!=='decode','本人だけの傷の情報を相談へ漏らす');shareClue('ines','etching');chat=[];
 ok(cooperationConversation('壁の傷の文字を解読して','brom')&&chat[0].text.includes('マレン')&&currentOffers().lydia?.action==='decode'&&!knowsClue('lydia','darkness'),'不得意な解読依頼から適任者への申し出につながらないか先に解読');
 fixture();state.room='hall';reportInvestigation(PEOPLE[1],'inspect',apply('brom','inspect'));
 ok(currentOffers().gareth?.action==='unlock','ブロムの扉の実結果から適任者が申し出ない');
 apply('gareth','unlock');chat=[];cooperationConversation('次は何をすればいい？','all');
 ok(chat.at(-1).text.includes('水の圧力')&&!chat.at(-1).text.includes('排水室')&&!state.supported,'未排水で支援か未訪問地名を案内');
 state.drained=true;state.observedDrain=true;
 ok(conversationProgress().find(t=>t.target==='door').reporters.includes('ブロム'),'排水による描写変化で共有済みの調査を忘れる');
 ok(cooperationAdvice().action==='support','排水・解錠後に支援を申し出ない');apply('brom','support');
 ok(cooperationAdvice().action==='crawl','工具がなくても潜入の代案を示さない');acquireItem('ines','ironbar');
 ok(cooperationAdvice().action==='wedge','工具を持つ本人の固定へつながらない');apply('ines','wedge');
 ok(!cooperationAdvice().action&&cooperationAdvice().speech.includes('もう開いて'),'開通後に扉の作業を勧める');
 fixture();state.room='hall';reportInvestigation(PEOPLE[2],'inspect',apply('gareth','inspect'));state.items.picks.holder='brom';chat=[];
 ok(cooperationConversation('石扉の鍵を外して','gareth')&&chat[0].text.includes('ブロム')&&chat[0].text.includes('貸して'),'能力があっても道具がない理由を伝えない');
 fixture();apply('brom','inspect_cart');publishReport('brom',inspectText('brom','cart',state));apply('ines','take');
 chat=[{kind:'you',text:'何か他に気になるものはある？'}];const updatedInput=dialogueInput(PEOPLE[2],false,null,null);
 ok(!updatedInput.proposalChoices.inspect_cart&&updatedInput.proposalChoices.inspect_rails&&updatedInput.nextStep.action==='inspect_rails','取得済みの台車を自由会話の提案候補に残す');
 apply('gareth','inspect_rails');publishReport('gareth',inspectText('gareth','rails',state));
 ok(!dialogueInput(PEOPLE[3],false,null,null).proposalChoices.inspect_rails&&!cooperationAdvice().action,'実結果共有後に同じハズレ調査を頼む');
 fixture();state.room='drain';
 for(const text of ['もし操作輪の鉄片を外してと言ったら','操作輪の鉄片を外さないで','次は反対の道に行こう','操作輪の鉄片を外せる？'])ok(!cooperationConversation(text,'brom')&&actionHistory.length===0,'仮定・反対・能力質問を実行依頼として取り扱う');
 fixture();
 ok(!cooperationConversation('次は何が得意か教えて','brom')&&!cooperationConversation('次はどう育ったか聞かせて','lydia'),'人物質問を進行案内へすり替える');
 state.room='drain';chat=[];cooperationConversation('操作輪の鉄片を外して','gareth');
 ok(currentOffers().gareth?.action==='inspect_wheel'&&!chat.some(c=>c.text.includes('イネスが得意'))&&actionHistory.length===0,'未調査の依頼から状態確認へ戻さないか役割を先に暴露');
 state.lit=false;ok(cooperationAdvice()===null&&!cooperationConversation('次は何をすればいい？','all'),'暗闇で未発見対象を案内');state.lit=true;state.phase='battle';
 ok(cooperationAdvice()===null&&!cooperationConversation('操作輪を支えて','brom'),'戦闘へ探索の分担を混ぜる');state.phase='explore';
 ok(!cooperationConversation('次は何をすればいい？','gm'),'GM宛ての質問を仲間が奪う');
 fixture();explorationOffers.gareth={room:'entry',action:'inspect_rails'};reportInvestigation(PEOPLE[1],'inspect_rails',apply('brom','inspect_rails'));
 ok(!currentOffers().gareth,'他者の共有結果で不要になった古い申し出が残る');
 fixture();state.room='drain';explorationOffers.gareth={room:'drain',action:'inspect_wheel'};state.drained=true;
 ok(!currentOffers().gareth&&!dialogueInput(PEOPLE[2],false,null,null).proposalChoices.inspect_wheel,'排水後も輪を調べる古い申し出・提案候補が残る');
 fixture();state.room='hall';state.opened=true;
 ok(!dialogueInput(PEOPLE[2],false,null,null).proposalChoices.inspect,'開通済みの扉を調べる自発候補が残る');
 fixture();chat=[];const beforeSubmitUI=updateRecipients;updateRecipients=()=>{};await submitMessage('次は何をすればいい？','brom');updateRecipients=beforeSubmitUI;
 ok(currentOffers().brom?.action==='inspect_cart'&&actionHistory.length===0&&chat.at(-1).text.includes('古い台車'),'入力欄から次の相談へ接続できないか了承前に調査');
 fixture();const ownActionUI=updateRecipients;updateRecipients=()=>{};
 apply('brom','inspect_cart');publishReport('brom',inspectText('brom','cart',state));askHuman('brom','take','イネス、工具を拾ってくれるか？');
 ok(currentHumanRequests('brom')[0]?.action==='take'&&!state.items.ironbar,'人間への依頼がないか了承前に取得');
 ok(humanMessageIntent('うん、拾うわ','brom').action==='take'&&humanMessageIntent('はい','brom').requester==='brom','自分の短い返事を識別できない');
 ok(humanMessageIntent('はい','gareth')===null,'指定外の相手の人間依頼を了承');
 $('sheet').open=true;await submitMessage('ちょっと待って','brom');
 ok(!state.items.ironbar&&currentHumanRequests('brom')[0].paused&&$('sheet').open&&chat.at(-1).text.includes('待つ'),'待ってで実行か依頼・シートを破棄');
 ok(dialogueInput(PEOPLE[1],false,null,null).humanRequests[0].paused,'保留した依頼を本人の会話へ渡さない');
 const acted=await submitMessage('うん、拾うわ','brom');
 ok(acted.performed&&hasItem('ines','ironbar')&&!$('sheet').open&&actionHistory.at(-1).id==='ines'&&actionHistory.at(-1).initiator==='ines','返事から本人が取得・シート閉鎖されないか履歴が他者の行動');
 ok(!currentHumanRequests().length&&chat.some(c=>c.who==='ブロム（AI）'&&c.text.includes('拾ってくれて助かる')),'実結果の受け答えか依頼の消費がない');
 const actionCount=actionHistory.length;await submitMessage('私が工具を拾う','all');ok(actionHistory.length===actionCount,'取得を二重実行');
 fixture();apply('brom','inspect_cart');publishReport('brom',inspectText('brom','cart',state));askHuman('brom','take','イネス、工具を拾って');
 explorationOffers.brom={room:'entry',action:'inspect_rails'};
 ok(humanMessageIntent('はい','brom').clarify&&!state.items.ironbar,'本人の申し出と人間への依頼の両方を了承');
 explorationOffers={};state.navigation.offer={holder:'lydia',item:'lydia_map',room:'entry'};
 ok(humanMessageIntent('うん','all').clarify,'地図の申し出と人間の作業を同時に了承');state.navigation.offer=null;
 pendingTransfer={};ok(humanMessageIntent('はい','brom').clarify,'受け渡しの保留へ了承を流用');pendingTransfer=null;
 consents.lantern=mergeConsentSignals('lantern',null,[{id:'lydia',action:'douse',stance:'question',quote:'待って'}]);
 ok(humanMessageIntent('はい','all').clarify,'灯りの保留と人間の作業を了承');consents={};
 for(const text of ['工具を拾える？','もし私が工具を拾う','私が工具を拾った','工具を拾うつもり','工具を拾うのはやめる','ブロムが工具を拾う','「工具を拾う」と言う','後で工具を拾う','工具を拾わない'])ok(humanMessageIntent(text,'brom')===null&&!state.items.ironbar,'質問・仮定・過去・予定・否定・他人の発言から取得');
 ok(humanMessageIntent('私が工具を拾う','gm')===null,'GMへの相談で人間の行動を実行');
 await submitMessage('やめる','brom');ok(!humanRequests.length&&!state.items.ironbar,'断った依頼を残すか実行');
 ok(humanMessageIntent('工具を拾って、隙間を固定する','all').clarify,'複数の自分の行動を同時に実行');
 fixture();ok(humanMessageIntent('私が工具を拾う','all').clarify&&!state.items.ironbar,'未調査の工具を取得');
 apply('brom','inspect_cart');publishReport('brom',inspectText('brom','cart',state));rememberHumanRequest('gareth','イネス、工具を拾ってくれるか？');
 ok(currentHumanRequests('gareth').length===1,'人物照合後の自由発言から依頼を記録しない');
 rememberHumanRequest('lydia','イネス、工具を拾わないで');ok(!currentHumanRequests('lydia').length,'取り止めの発言を依頼として記録');
 move('hall');move('entry');ok(!humanRequests.length&&humanMessageIntent('はい','gareth')===null,'移動と帰還で古い依頼を使う');
 fixture();state.room='hall';state.locked=false;state.drained=true;state.supported=true;acquireItem('ines','ironbar');
 cooperationFollowup('brom','support');ok(currentHumanRequests()[0].action==='wedge','支えから人間の固定への依頼がない');
 askHuman('lydia','crawl','イネス、隙間へ入って留め具を外して');
 ok(humanMessageIntent('はい','all').clarify&&!state.opened,'二つの自分の作業を曖昧な了承で選ぶ');
 const fixed=await submitMessage('私が工具で隙間を固定する','all');
 ok(fixed.performed&&state.opened&&actionHistory.at(-1).action==='wedge'&&!currentHumanRequests().length,'明確な宣言で固定しないか他の古い作業を残す');
 fixture();state.room='hall';state.locked=false;state.drained=true;state.supported=true;
 cooperationFollowup('brom','support');ok(currentHumanRequests()[0].action==='crawl','工具なしの潜入を依頼しない');
 $('sheet').open=true;const crawled=await submitMessage('うん','brom');
 ok(crawled.performed&&state.opened&&actionHistory.at(-1).action==='crawl'&&!$('sheet').open,'短い了承から潜入・シート閉鎖されない');
 ok(chat.some(c=>c.who==='ブロム（AI）'&&c.text.includes('留め具が外れた')),'潜入の実結果を仲間が受け止めない');
 fixture();state.room='hall';state.locked=false;state.supported=true;acquireItem('ines','ironbar');askHuman('brom','wedge','イネス、隙間を固定して');
 state.items.ironbar.holder='gareth';ok(humanMessageIntent('はい','brom').clarify&&!state.opened,'返事の時点で工具の所持を再確認しない');
 state.items.ironbar.holder='ines';state.supported=false;ok(humanMessageIntent('はい','brom').clarify&&!state.opened,'支えがなくなった古い依頼を実行');
 state.supported=true;state.lit=false;ok(humanMessageIntent('私が工具で隙間を固定する','all').clarify&&!state.opened,'暗闇でも固定を実行');
 state.lit=true;state.phase='battle';ok(humanMessageIntent('私が工具で隙間を固定する','all')===null,'戦闘へ探索の実行を持ち込む');state.phase='explore';generation++;
 ok(humanMessageIntent('はい','brom')===null,'世代が変わった依頼を了承');updateRecipients=ownActionUI;
 fixture();positionGM=()=>{};renderPlacement=()=>{};placeTargetLabels=()=>{};updateRecipients=()=>{};redrawEffects=()=>{};refreshOpenSheet=()=>{};target='cart';realRender();
 ok(!$('actions').innerHTML.includes('data-request')&&$('actions').innerHTML.includes('data-act="inspect_cart"'),'調査ポイントに他者の選択肢が残る');
 // 2026-10-07：了承と判定されても、宛先・名指しで相手が一人に決まる時だけ依頼として扱います。決まらなければ実行しません。
 const hold=(text,to)=>{try{return validateExplorationIntent({kind:'approval',jobs:[{id:'brom',action:'hold',quote:text}],clarify:''},to,text);}catch(e){return {error:e.message};}};
 fixture();state.room='drain';
 ok(hold('操作輪を支えて','brom').jobs?.[0]?.action==='hold','宛先のブロムへの支えの依頼を、申し出が無いからと却下');
 ok(!hold('操作輪を支えて','all').jobs?.length,'宛先も名指しも無い了承で、申し出の無い支えを実行');
 explorationOffers={brom:{room:'drain',action:'hold'},gareth:{room:'drain',action:'inspect_water'},lydia:{room:'drain',action:'inspect_water'}};
 ok(hold('ブロム、操作輪を支えて','all').jobs?.[0]?.id==='brom','名指しされたブロムの申し出を選べない');
 ok(!hold('ブロムとガレス、操作輪を支えて','all').jobs?.length,'二人を名指しした了承で一人の申し出を実行');
 // 2026-10-07：短い了承は、一番新しい申し出に応えたとみなします。了承の言葉が無ければ実行しません。
 updateRecipients=()=>{};finishAITurn=()=>{};const noLLM=async()=>{throw Error('LLMを呼ばない');};
 const did=(id,action)=>actionHistory.some(h=>h.id===id&&h.action===action);
 fixture();busy=false;ask=noLLM;offerCooperation('lydia','inspect_rails','私がレールを調べてみましょうか？');offerCooperation('brom','inspect_rails','俺がレールを調べてみようか？');
 await submitMessage('お願い','all');ok(did('brom','inspect_rails')&&!did('lydia','inspect_rails'),'2つの申し出のうち一番新しいブロムの申し出に応えない');
 fixture();busy=false;ask=noLLM;offerCooperation('brom','inspect_rails','俺がレールを調べてみようか？');
 await submitMessage('そうだね。やってみて','all');ok(did('brom','inspect_rails'),'「そうだね。やってみて」を了承と読まない');
 fixture();busy=false;ask=noLLM;offerCooperation('brom','inspect_rails','俺がレールを調べてみようか？');
 await submitMessage('そうだね','all');ok(!did('brom','inspect_rails'),'了承の言葉が無い相づちで実行');
 fixture();busy=false;ask=noLLM;offerCooperation('brom','inspect_rails','俺がレールを調べてみようか？');
 await submitMessage('お願い','gareth');ok(!did('brom','inspect_rails'),'別の相手への「お願い」でブロムの申し出を実行');
 // 2026-10-07：説明の文の後ろにJSONの囲み（バッククォート3つ＋json）が1つだけある返答は、その中身を読みます。囲みが2つ・文だけは今どおり拒否します。
 const fence=body=>'\\x60\\x60\\x60json\\n'+body+'\\n\\x60\\x60\\x60';
 ok(parseAI('石扉の広間か、いい判断だな。\\n\\n'+fence('{"speech":"行こう","action":"wait"}')).speech==='行こう','説明の文の後ろのJSONを読めない');
 ok(parseAI(fence('{"speech":"行こう"}')).speech==='行こう'&&parseAI('{"speech":"行こう"}').speech==='行こう','これまで読めた形が読めない');
 ok(rejects(()=>parseAI('前置き\\n'+fence('{"action":"wait"}')+'\\n'+fence('{"action":"smash"}'))),'JSONの囲みが2つある返答から恣意的に1つを選ぶ');
 ok(rejects(()=>parseAI('石扉の広間か、いい判断だな。')),'JSONの無い返答を受理');
 // 2026-10-07：暗くて誰も調べられない時の調べる依頼には、GMが先に理由と灯りの頼み先を返します。依頼でない発言や明るい時は止めません。
 fixture();apply('lydia','douse');state.discovery.cache=true;ask=async()=>{throw Error('LLMを呼ばない');};
 const darkAsk=await explorationIntent('隠し収納を調べてくれる？','gareth');ok(darkAsk.clarify.startsWith('暗くて')&&darkAsk.clarify.includes('マレン')&&!darkAsk.jobs.length,'暗闇の調査依頼にGMが理由と灯りの持ち主を返さない');
 ok((await explorationIntent('隠し収納の開け方が分からない','all')).clarify==='','暗闇の相談まで依頼として止める');
 fixture();ok(!explorationBlockedReason(),'明るい時に調査を止める理由を返す');
 // 2026-10-07：暗くて調べられない間は「〜が見えるよ。調べてみよう」と告知せず、灯した時に告知します。GM相談には調べられない理由を渡します。
 fixture();apply('lydia','douse');state.discovery.cache=true;announcedPoints=new Set();chat=[];
 announceVisiblePoints();ok(!chat.some(c=>c.text.includes('見えるよ')),'暗闇で「見えるよ。調べてみよう」と告知');
 apply('lydia','light');chat=[];announceVisiblePoints();ok(chat.some(c=>c.text.includes('「隠し収納」')&&c.text.includes('見えるよ')),'灯した後に隠し収納を告知しない');
 fixture();apply('lydia','douse');state.discovery.cache=true;let gmSystem='',gmInput=null;ask=async(system,payload)=>{gmSystem=system;gmInput=payload;return '暗くて調べられません。';};
 await consultGM('隠し収納の開け方が分からない');ok(gmInput?.blocked?.startsWith('暗くて')&&gmSystem.includes('blocked'),'GM相談に暗くて調べられない理由を渡さない');
 fixture();gmInput=null;await consultGM('隠し収納の開け方が分からない');ok(gmInput&&gmInput.blocked===null,'明るい時のGM相談に調べられない理由を渡す');
 return count;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 明示依頼と短い了承 / 曖昧な提案の確認 / 指定相手・発言根拠 / 調査と実結果の共有 / 個人情報の保護 / 解読 / 候補の自発共有 / 二重実行・古い応答 / 会話から解錠判定 / 自分だけの選択肢 / 人間への依頼・保留・了承・自分の実行')).catch(e=>{console.error(e);process.exitCode=1;});
