const fs=require('node:fs'),vm=require('node:vm');
const loadPrototype=require('./load-prototype.cjs').load;
const elements={},element=()=>({innerHTML:'',style:{},classList:{toggle(){}},querySelectorAll(){return []},open:false,close(){this.open=false;}});
const context=vm.createContext({document:{getElementById(id){return elements[id]??=element();}},crypto:require('node:crypto').webcrypto});
loadPrototype(context);
vm.runInContext(`(async()=>{
 let count=0;const ok=(v,m)=>{count++;if(!v)throw Error(m)},rejects=fn=>{try{fn();return false}catch{return true}};
 render=()=>{};say=(who,text,kind='')=>chat.push({who,text,kind});
 const fixture=()=>{state=initial();actionHistory=[];chat=[];plan=[];consents={};pendingTransfer=null;};fixture();
 const give=(item,from,to,mode='give')=>({item,from,to,mode});
 ok(Object.keys(state.items).length===8&&Object.values(state.items).every(r=>r.owner===r.holder),'初期装備の所有者が不正');
 ok(inventoryView('brom').items.length===2&&!inventoryView('brom').others.some(i=>i.id==='rope'),'他人の未開示の持ち物をAIに漏らす');
 ok(actionsFor('lydia').includes('light')&&!actionsFor('ines').includes('light'),'初期のランタン所持者が不正');
 ok(!publicView().inventory.some(i=>i.id==='rope')&&publicView().inventory.some(i=>i.id==='lantern'),'公開の持ち物の境界が不正');
 apply('lydia','light');apply('ines','inspect_cart');apply('ines','take');
 ok(hasItem('ines','ironbar')&&!hasItem('brom','ironbar'),'拾った工具が共有');
 ok(rejects(()=>acquireItem('brom','ironbar'))&&Object.keys(state.items).length===9,'同じ品を二重取得');
 const gift=transferItem(give('ironbar','ines','brom'));
 ok(state.items.ironbar.owner==='brom'&&hasItem('brom','ironbar')&&!hasItem('ines','ironbar'),'譲渡で所有者・所持者が変わらない');
 ok(knownItems('brom').some(i=>i.id==='ironbar')&&!profileFacts('ines').item_ironbar&&profileFacts('brom').item_ironbar.value==='鉄の工具','シートと正本の持ち物が古い');
 ok(state.transfers.length===1&&actionHistory.filter(h=>h.transfer).length===2&&sheetInformation('brom').history.some(h=>h.transfer),'双方の受け渡し履歴がない');
 ok(state.profiles.history.some(h=>h.id==='ines'&&h.value==='鉄の工具'),'以前の開示記録が所有変更で消える');
 ok(transferSummary(gift).includes('譲渡')&&inventoryView('brom').history[0].item==='ironbar','誠意を表す受け渡しの記憶がない');
 state.room='drain';apply('brom','hold');ok(!actionsFor('ines').includes('pry'),'持っていない工具で作業できる');
 transferItem(give('ironbar','brom','ines','lend'));ok(state.items.ironbar.owner==='brom'&&hasItem('ines','ironbar')&&actionsFor('ines').includes('pry'),'借りた工具を使えない');
 ok(rejects(()=>transferItem(give('ironbar','ines','gareth')))&&rejects(()=>transferItem(give('ironbar','ines','gareth','lend'))),'借りた品を譲渡か又貸しできる');
 ok(rejects(()=>transferItem(give('ironbar','ines','lydia','return'))),'貸主以外へ返却できる');
 apply('ines','pry');ok(state.drained,'借りた工具で排水できない');
 transferItem(give('ironbar','ines','brom','return'));ok(state.items.ironbar.owner==='brom'&&hasItem('brom','ironbar')&&!hasItem('ines','ironbar'),'返却で所持者が戻らない');
 ok(Object.keys(state.items).length===9&&state.transfers.length===3,'受け渡しで品が増える');
 transferItem(give('ironbar','brom','ines','return'));ok(hasItem('ines','ironbar')&&state.items.ironbar.owner==='ines','譲った品を本人の了承で返してもらえない');
 fixture();transferItem(give('lantern','lydia','ines','lend'));ok(!actionsFor('lydia').includes('light')&&actionsFor('ines').includes('light'),'ランタンの所持者と操作権が一致しない');
 ok(lanternRequest('ランタンを灯して','lydia')==='light'&&lanternRequest('ランタンを灯して','brom')===null,'持っていない仲間の依頼を勝手に変更');
 apply('ines','light');ok(state.lit,'借りたランタンを使えない');transferItem(give('lantern','ines','lydia','return'));ok(state.lit&&actionsFor('lydia').includes('douse'),'返却で点灯状態が失われる');
 fixture();state.phase='battle';transferItem(give('hammer','brom','ines'));ok(!actionsFor('brom').includes('strike')&&actionsFor('brom').includes('cover')&&!actionsFor('ines').includes('strike'),'装備を持たない攻撃または譲渡で技能を習得');
 fixture();state.phase='battle';plan=[{id:'brom',action:'cover'}];planReview={};
 equipItem('brom','shield',false);ok(hasItem('brom','shield')&&!actionsFor('brom').includes('cover')&&actionsFor('brom').includes('strike')&&!plan.length&&!planReview,'着脱で所持・行動・計画が一致しない');
 equipItem('brom','shield',true);ok(actionsFor('brom').includes('cover'),'再装備でかばうが戻らない');
 transferItem(give('shield','brom','ines','lend'));ok(!state.items.shield.equipped&&state.items.shield.owner==='brom'&&stageSnapshot().actors.every(p=>!p.equipment.includes('shield')),'貸与直後に誰かが自動装備');
 equipItem('ines','shield',true);placement=makePlacement(true);ok(stageSnapshot().actors.find(p=>p.id==='ines').equipment.includes('shield')&&!actionsFor('ines').includes('cover'),'借り手への表示または技能の境界が不正');
 transferItem(give('shield','ines','brom','return'));ok(!state.items.shield.equipped&&!actionsFor('brom').includes('cover'),'返却時に自動装備');
 ok(rejects(()=>equipItem('ines','shield',true))&&rejects(()=>equipItem('brom','shield','true')),'未所持または不正な装備値を受理');
 ok(equipmentIntent('ブロム、盾を外してください','all').equipped===false&&equipmentIntent('盾を装備してください','brom').equipped===true&&!equipmentIntent('もし盾を外すなら','brom'),'会話の着脱依頼と仮定を取り違え');
 ok(!equipmentIntent('私が工具で鉄片を外す','all')&&!equipmentIntent('ガレス、錠前を外して','gareth')&&!equipmentIntent('留め具を外す','all'),'探索の取り外しを装備の着脱へ横取りする');
 fixture();state.phase='battle';transferItem(give('hammer','brom','ines'));
 transferItem(give('staff','lydia','ines'));ok(!actionsFor('lydia').includes('fire')&&!actionsFor('lydia').includes('spark')&&actionsFor('lydia').includes('retreat'),'杖なしで魔法か撤退まで消える');
 plan=[{id:'lydia',action:'fire'}];planReview={};transferItem(give('staff','ines','lydia'));ok(!plan.length&&!planReview,'装備変更で古い戦闘計画が残る');
 fixture();acquireItem('ines','ironbar');
 ok((await transferIntent('これを渡すわ','lydia')).clarify,'複数アイテムから勝手に選択');
 ok(transferCandidates('この工具、ブロムに渡すわ','all').length===1,'自然な工具譲渡が特定できない');
 ok(!transferCandidates('この工具、ガレスに渡すわ','brom').length,'宛先と発言の相手が違う');
 transferItem(give('ironbar','ines','brom'));ok(!transferCandidates('工具をブロムに渡すわ','brom').length,'持っていない品の受け渡しを逆向きに実行');
 ok(transferCandidates('工具を貸して','brom')[0].mode==='lend','貸してを譲渡と取り違え');
 ok(transferCandidates('ブロム、その工具を少し貸して。仕掛けを調べたら返すわ','brom')[0].from==='brom','返却の約束を今の返却と取り違え');
 const realAsk=ask;let calls=0;
 fixture();const equipment={who:'brom',item:'shield',equipped:false};
 ask=async()=>JSON.stringify({decision:'decline',speech:'今は装備しておく。'});auditProfile=async()=>({valid:true,claims:[],conflicts:[]});
 ok(!(await handleEquipment(equipment,'盾を外してください')).performed&&state.items.shield.equipped,'拒否でも装備を外す');
 ask=async()=>JSON.stringify({decision:'accept',speech:'分かった、外そう。'});ok((await handleEquipment(equipment,'盾を外してください')).performed&&!state.items.shield.equipped,'本人了承後も外れない');
 fixture();ask=async()=>{transferItem(give('shield','brom','ines','lend'));return JSON.stringify({decision:'accept',speech:'分かった。'})};let equipmentBad=false;try{await handleEquipment(equipment,'盾を外してください')}catch{equipmentBad=true}ok(equipmentBad&&hasItem('ines','shield'),'受け渡し後の古い了承で着脱');
 ok(!equipmentIntent('盾を装備している？','brom')&&!equipmentIntent('盾を貸して、装備してください','brom')&&equipmentIntent('ガレス、盾を外してください','brom').clarify,'質問・複合依頼・宛先違いを実行');
 fixture();acquireItem('ines','ironbar');transferItem(give('ironbar','ines','brom'));
 ask=async()=>{calls++;return JSON.stringify({kind:'request',index:0,quote:'工具を貸して'})};
 const borrowed=await transferIntent('工具を貸して','brom');ok(borrowed.transfer.from==='brom'&&borrowed.transfer.to==='ines','借りる人と貸す人を逆転');
 ok((await transferIntent('もし工具を借りたら？','brom'))===null&&(await transferIntent('工具を貸さないで','brom'))===null&&calls===0,'仮定・禁止で受け渡し');
 ok((await transferIntent('工具を貸して','all')).clarify,'相手なしで勝手に借りる');
 ask=async()=>JSON.stringify({kind:'request',index:0,quote:'偽の依頼'});let bad=false;try{await transferIntent('工具を借りたい','brom')}catch{bad=true}ok(bad,'未発言の引用で受け渡し');
 ask=async()=>{generation++;return JSON.stringify({kind:'request',index:0,quote:'工具を貸して'})};ok((await transferIntent('工具を借りたい','brom')).stale,'リセット前の意思を受理');
 ask=async()=>JSON.stringify({kind:'conversation',index:0,quote:''});ok((await transferIntent('貸してくれてありがとう','brom'))===null,'貸与への感謝を新しい依頼と扱う');
 fixture();acquireItem('ines','ironbar');const t=give('ironbar','ines','brom');
 auditProfile=async()=>({valid:true,claims:[],conflicts:[]});
 ask=async()=>JSON.stringify({decision:'decline',speech:'今はイネスが使っていてくれ。'});ok(!(await handleTransfer(t,'工具を渡す')).performed&&hasItem('ines','ironbar')&&!state.transfers.length,'拒否でも受け渡す');
 ask=async()=>JSON.stringify({decision:'question',speech:'貸してくれるのか？'});ok(!(await handleTransfer(t,'工具を渡す')).performed&&hasItem('ines','ironbar'),'質問中に受け渡す');
 ok((await transferIntent('うん、どうぞ','brom')).transfer.item==='ironbar','保留した受け渡しを短い了承で継続できない');
 ok((await transferIntent('やめておく','brom')).cancelled&&!pendingTransfer&&hasItem('ines','ironbar'),'会話で受け渡しを取り消せない');
 ask=async()=>{throw Error('接続失敗')};let failed=false;try{await handleTransfer(t,'工具を渡す')}catch{failed=true}ok(failed&&hasItem('ines','ironbar'),'通信失敗で持ち物が変わる');
 ask=async()=>JSON.stringify({decision:'accept',speech:'ありがとう。大事に使わせてもらう。'});auditProfile=async()=>({valid:false,claims:[],conflicts:[{}]});failed=false;try{await handleTransfer(t,'工具を渡す')}catch{failed=true}ok(failed&&hasItem('ines','ironbar'),'設定照合の失敗で受け渡す');
 auditProfile=async()=>({valid:true,claims:[],conflicts:[]});const success=await handleTransfer(t,'工具を渡す');ok(success.performed&&hasItem('brom','ironbar')&&chat.some(c=>c.text.includes('ありがとう')),'感謝と実際の受け渡しが両立しない');
 ok(state.shared.some(x=>x.includes('譲渡'))&&chat.some(c=>c.kind==='gm'&&c.text.includes('持ち物を更新')),'確定した受け渡しが会話とクロニクルにない');
 fixture();acquireItem('ines','ironbar');ask=async()=>{generation++;return JSON.stringify({decision:'accept',speech:'ありがとう。'})};ok(!(await handleTransfer(t,'工具を渡す')).performed&&hasItem('ines','ironbar'),'古い了承で所有者を変更');
 fixture();acquireItem('ines','ironbar');ask=async()=>{transferItem(t);return JSON.stringify({decision:'accept',speech:'ありがとう。'})};failed=false;try{await handleTransfer(t,'工具を渡す')}catch{failed=true}ok(failed&&state.transfers.length===1,'並行の所有変更後に二重実行');
 fixture();ok(!state.transfers.length&&hasItem('lydia','lantern')&&Object.keys(state.items).length===8,'最初からで所有状態が残る');
 return count;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 個別所有 / 入手 / 譲渡・貸与・返却 / 装備と能力 / シートと記憶 / 宛先・曖昧な品 / 拒否と保留 / 通信・設定照合・古い応答 / 二重移動防止')).catch(e=>{console.error(e);process.exitCode=1});
