const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const context=vm.createContext({document:{getElementById(){}},crypto:require('node:crypto').webcrypto});
vm.runInContext(source.split("$('chat').onsubmit")[0],context);
vm.runInContext(`(async()=>{
 let count=0;const ok=(x,m)=>{count++;if(!x)throw Error(m);},rejects=fn=>{try{fn();return false;}catch{return true;}};
 state=initial();render=()=>{};say=(who,text,kind='')=>chat.push({who,text,kind});
 const signal=(id,action,stance,quote='発言')=>({id,action,stance,quote});
 let d=mergeLanternSignals(null,[signal('lydia','light','request')]);
 ok(lanternCandidate(d)===null,'本人の提案だけで持ち物質問を実行した');
 d=mergeLanternSignals(d,[signal('brom','light','request')]);ok(lanternCandidate(d)==='light','仲間の依頼を実行できない');
 d=mergeLanternSignals(d,[signal('ines','light','oppose')]);ok(lanternCandidate(d)===null,'本人の反対を無視');
 d=mergeLanternSignals(d,[signal('gareth','light','request')]);ok(lanternCandidate(d)===null,'多数の賛成で反対を消した');
 d=mergeLanternSignals(d,[signal('brom','light','withdraw')]);ok(d.voices['ines:light'].stance==='oppose','他人の撤回で反対を消した');
 d=mergeLanternSignals(d,[signal('ines','light','withdraw')]);ok(lanternCandidate(d)==='light','本人の撤回後も保留');
 d=mergeLanternSignals(d,[signal('ines','light','question')]);ok(lanternCandidate(d)===null,'疑問が残ったまま実行');
 d=mergeLanternSignals(d,[signal('ines','light','request')]);ok(lanternCandidate(d)==='light','本人が納得しても疑問が消えない');
 d=mergeLanternSignals(d,[signal('gareth','douse','request')]);ok(lanternCandidate(d)===null,'点灯と消灯が食い違っても実行');
 lanternDiscussion=d;ok(lanternBlocked(),'相反する依頼で明示命令を通した');
 const lit=initial();lit.lit=true;ok(lanternCandidate(mergeLanternSignals(null,[signal('brom','light','request')],lit),lit)===null,'点灯済みを再実行');
 ok(lanternCandidate(mergeLanternSignals(null,[signal('brom','douse','request')],lit),lit)==='douse','消灯の同意で実行不可');
 const battle=initial();battle.phase='battle';ok(lanternCandidate(d,battle)===null,'戦闘で探索の灯りを操作');
 const other=initial();other.room='hall';ok(lanternCandidate(d,other)===null,'別シーンの相談を流用');
 lanternDiscussion=d;state.room='hall';ok(currentLanternDiscussion()===null,'移動で保留が破棄されない');state=initial();
 const lines=[{index:2,id:'ines',text:'点灯は反対。'},{index:3,id:'brom',text:'リディア、灯してくれ。'}];
 const compound=validateLanternSignals({signals:[{index:3,action:'light',stance:'request',quote:'灯して'},{index:3,action:'light',stance:'withdraw',quote:'灯して'}]},lines);ok(compound[0].stance==='withdraw'&&compound[1].stance==='request','撤回と賛成の複合発言で賛成が消える');
 const validated=validateLanternSignals({signals:[{index:2,action:'light',stance:'oppose',quote:'点灯は反対'}]},lines);ok(validated[0].id==='ines','発言者が不正');ok(validateLanternSignals([{index:3,action:'light',stance:'request',quote:'灯して'}],lines)[0].id==='brom','実GMの配列形式を扱えない');
 ok(rejects(()=>validateLanternSignals({signals:[{index:3,action:'light',stance:'request',quote:'消して'}]},lines)),'未発言の根拠を受理');
 ok(rejects(()=>validateLanternSignals({signals:[{index:9,action:'light',stance:'request',quote:'灯して'}]},lines)),'未知の発言を受理');
 ok(rejects(()=>validateLanternSignals({signals:[{index:3,action:'smash',stance:'request',quote:'灯して'}]},lines)),'対象外の行動を受理');
 ok(rejects(()=>validateLanternSignals({signals:[{index:3,action:'light',stance:'request',quote:'灯して'},{index:3,action:'light',stance:'oppose',quote:'灯して'}]},lines)),'同じ発言の重複を受理');
 function fixture(){state=initial();lanternDiscussion=null;actionHistory=[];chat=[{who:'イネス（あなた）→全員',kind:'you',text:'誰か灯りを持ってる？'},{who:'ブロム（AI）',kind:'',text:'リディア、灯してくれ。'}];}
 const gmSignals=JSON.stringify({signals:[{index:1,action:'light',stance:'request',quote:'灯してくれ'}]});
 auditProfile=async()=>({valid:true,claims:[],conflicts:[]});
 fixture();let calls=0;ask=async()=>++calls===1?gmSignals:JSON.stringify({speech:'うん、灯すわ。',action:'light'});await settleLantern(0);
 ok(state.lit&&actionHistory.length===1&&actionHistory[0].initiator==='lydia','了承から自発点灯・行動記録が成立しない');
 ok(lanternDiscussion===null,'完了した相談が残る');
 calls=0;ask=async()=>++calls===1?gmSignals:JSON.stringify({speech:'灯すわ。',action:'light'});await settleLantern(0);ok(actionHistory.length===1&&calls===1,'実行済みを二重実行');
 fixture();calls=0;ask=async()=>++calls===1?gmSignals:JSON.stringify({speech:'少し待って、足元を確かめたいわ。',action:'wait'});await settleLantern(0);
 ok(!state.lit&&actionHistory.length===0&&lanternBlocked(),'本人の保留を無視');
 fixture();calls=0;ask=async()=>++calls===1?gmSignals:JSON.stringify({speech:'扉を壊すわ。',action:'smash'});let wrong=false;try{await settleLantern(0);}catch{wrong=true;}ok(wrong&&!state.lit&&actionHistory.length===0,'別の行動を実行');
 fixture();ask=async()=>{throw Error('通信失敗');};let disconnected=false;try{await settleLantern(0);}catch{disconnected=true;}ok(disconnected&&!state.lit&&actionHistory.length===0,'接続失敗で実行');
 fixture();ask=async()=>{generation++;return gmSignals;};await settleLantern(0);ok(!state.lit&&actionHistory.length===0,'古い応答で実行');
 fixture();calls=0;ask=async()=>++calls===1?gmSignals:JSON.stringify({speech:'灯すわ。',action:'light'});auditProfile=async()=>({valid:false,claims:[],conflicts:[{}]});let mismatch=false;try{await settleLantern(0);}catch{mismatch=true;}ok(mismatch&&!state.lit&&actionHistory.length===0,'人物照合の失敗を無視');
 return count;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 仲間の依頼 / 本人の了承・保留 / 反対・疑問・撤回 / 相反する案 / 点灯済み / 二重実行防止 / 発言根拠 / シーン・戦闘の制限 / 通信・形式・人物照合の失敗 / 古い応答')).catch(e=>{console.error(e);process.exitCode=1;});
