const fs=require('node:fs'),vm=require('node:vm');
const script=fs.readFileSync(__dirname+'/game.js','utf8');
const elements={};
function element(){const classes=new Set();return {innerHTML:'',textContent:'',dataset:{},style:{},open:false,classList:{add(c){classes.add(c)},remove(c){classes.delete(c)},contains(c){return classes.has(c)},toggle(){}},setAttribute(){},removeAttribute(){},querySelectorAll(){return []},close(){this.open=false},showModal(){this.open=true}};}
const context=vm.createContext({document:{getElementById(id){return elements[id]??=element()}},crypto:require('node:crypto').webcrypto});
vm.runInContext(script,context,{filename:__dirname+'/game.js'});
vm.runInContext(`(async()=>{
 let count=0;const ok=(value,message)=>{count++;if(!value)throw Error(message)},rejects=fn=>{try{fn();return false}catch{return true}};
 render=()=>{};updateRecipients=()=>{};announceVisiblePoints=()=>{};say=(who,text,kind='')=>chat.push({who,text,kind});
 const fixture=()=>{state=initial();chat=[];actionHistory=[];introduceInventory();chat=[];lanternDiscussion=null;pendingTransfer=null;explorationOffers={};recipient='all';busy=false;$('sheet').close();};
 fixture();
 ok(!visibleExits().length&&mapRecord().length===1,'暗闇で通路・未知の部屋を明示');
 ok(!hasItem('ines','ines_map')&&!Object.hasOwn(MAPS,'ines_map'),'イネスに試作用の坑道図が残る');
 const lit=apply('lydia','light');ok(!/石扉の広間|排水室/.test(lit.text),'点灯のGM文で未知の行き先を公開');
 ok(visibleExits().length===2&&visibleExits().every(e=>e.name===null)&&mapRecord().length===1,'見える通路と既知の地名を混同');
 ok(navigationIntent('排水室へ行こう').kind==='clarify','未確認の地名から自動で移動');
 ok(navigationIntent('下りの通路へ進もう').to==='drain','未知の通路を選んで入れない');
 ok(navigationIntent('奥へ進もう').kind==='route'&&navigationIntent('どっちに行く？').kind==='route','曖昧な進行を勝手に確定');
 ok(navigationIntent('リディア、地図を見せて').item==='lydia_map','紹介された相手の地図を特定できない');
 ok(navigationIntent('地図を見せて','lydia').holder==='lydia','個別の地図依頼が宛先と一致しない');
 ok(navigationIntent('地図を見せて','brom').kind==='clarify','地図を持たない相手への依頼を付け替え');
 ok(navigationIntent('坑道図を見せて').item==='lydia_map'&&navigationIntent('私の坑道図を広げよう').kind==='clarify','唯一の地図の特定や非所持品の拒否が不正');
 ok(navigationIntent('地図は持ってる？','lydia')===null,'所持品の質問だけで地図を開く');
 for(const text of ['もし排水室へ行くなら？','排水室へ行かないで','どっちにも行かないで','後で排水室へ行こう','排水室へ行く予定でした','地図を見せてもらった','地図を広げたわ','地図を広げてくれたね','排水室に行ってよかったね','排水室に行ったよ','入口へ戻ったわ','排水室へ行って欲しくない','地図を見せてほしくない','「排水室へ行こう」と言っていた'])ok(navigationIntent(text)===null,'相談・禁止・過去の発言で実行：'+text);
 const owner=JSON.stringify(state.items),visited=JSON.stringify(state.visited);readMap('lydia','lydia_map');
 ok(mapRecord().length===3&&visibleExits().every(e=>e.name),'地図を読んでも通路の行き先が分からない');
 ok(JSON.stringify(state.visited)===visited&&JSON.stringify(state.items)===owner,'地図を読むだけで訪問／譲渡');
 ok(mapRecord().filter(r=>!r.visited).every(r=>!r.note),'未訪問の地図に現在の仕掛け・水圧を公開');
 ok(navigationIntent('排水室に行こう').to==='drain'&&navigationIntent('広間に行こう').to==='hall','地図で知った部屋名・略称を指定できない');
 ok(navigationIntent('排水室へ行く？').kind==='route','移動の質問だけで移動');
 ok(navigationIntent('排水室へ行きましょうか').kind==='route','疑問符のない問いかけで移動');
 apply('lydia','douse');ok(!visibleExits().length&&mapRecord().length===3,'消灯で地図の記憶まで失う');
 ok(navigationIntent('排水室へ行こう').kind==='clarify','暗闇で通路へ移動');
 const before=JSON.stringify(state);ok(rejects(()=>readMap('lydia','lydia_map'))&&JSON.stringify(state)===before,'読めない地図で一部だけ状態更新');
 apply('lydia','light');move('drain');ok(mapRecord().find(r=>r.id==='drain').visited&&navigationIntent('入口に戻ろう').to==='entry','到着記録・戻る行動が不正');
 ok(navigationIntent('戻ろう').to==='entry','帰り道が一つの時にも戻れない');
 ok(navigationIntent('石扉の広間へ行こう').kind==='clarify','隣接していない部屋へ直接移動');
 move('entry');state.drained=true;ok(!mapRecord().find(r=>r.id==='hall').note,'未訪問の広間へ排水の変化が漏れる');
 fixture();apply('lydia','light');move('hall');move('entry');
 ok(visibleExits().find(e=>e.id==='hall').name==='石扉の広間'&&visibleExits().find(e=>e.id==='drain').name===null,'地図なしで訪ねた部屋と未訪問の部屋を区別できない');
 ok(mapRecord().length===2,'訪問だけで未訪問の分岐まで開示');
 fixture();state.discovery.stoneOn=true;readMap('lydia','lydia_map');ok(state.navigation.maps.includes('lydia_map')&&state.navigation.known.length===3,'灯石の灯りでリディアの地図を読めない');
 fixture();apply('lydia','light');const original=JSON.stringify(state);
 ok(rejects(()=>readMap('brom','lydia_map'))&&JSON.stringify(state)===original,'持っていない地図を読む');
 ok(rejects(()=>readMap('lydia','staff'))&&JSON.stringify(state)===original,'地図でない品を地図扱い');
 state.phase='battle';ok(rejects(()=>readMap('lydia','lydia_map'))&&!state.navigation.maps.length,'戦闘中に地図を開いて共有');
 fixture();apply('lydia','light');rememberMapOffer(PEOPLE[3],'私の地図を広げてみましょうか？');
 ok(currentMapOffer()?.holder==='lydia'&&navigationIntent('うん、お願い').kind==='map','本人の地図提案を短い了承で引き継げない');
 ok(navigationIntent('お願いします','brom')===null,'違う仲間への短い返事で地図を開く');
 pendingTransfer={item:'lantern'};ok(navigationIntent('お願いします').kind==='clarify'&&navigationIntent('見せて').kind==='map','複数の提案への曖昧な了承を地図へ確定');pendingTransfer=null;
 state.navigation.offer=null;rememberMapOffer(PEOPLE[3],'イネスの地図を見せてもらおう。');ok(!currentMapOffer(),'他人の地図への依頼を自分の提案に変換');
 rememberMapOffer(PEOPLE[3],'地図を広げたわ。');ok(!currentMapOffer(),'過去の話を提案にする');
 rememberMapOffer(PEOPLE[3],'私の地図を広げましょうか？');move('hall');ok(!currentMapOffer(),'別の場所に移動しても古い提案が残る');
 fixture();apply('lydia','light');transferItem({item:'lydia_map',from:'lydia',to:'brom',mode:'lend'});
 ok(navigationIntent('地図を見せて','brom').holder==='brom'&&navigationIntent('地図を見せて','lydia').kind==='clarify','貸した地図の現在の所持者を無視');
 readMap('brom','lydia_map');ok(state.items.lydia_map.owner==='lydia'&&state.items.lydia_map.holder==='brom','貸した地図を読むと所有者・所持者が変わる');
 // 本人の返答、GMの設定照合、再開始・移動・所有変更を挟んだ古い応答を実際の経路で検査。
 fixture();apply('lydia','light');let calls=0;ask=async()=>{calls++;return JSON.stringify({decision:'show',speech:'ええ、私の地図を広げます。'})};auditProfile=async()=>({valid:true,claims:[],conflicts:[]});
 ok((await requestMap('lydia','lydia_map')).performed&&calls===1&&$('sheet').open&&$('sheet').classList.contains('map-sheet'),'本人の了承から地図が表示されない');
 ok(sheetInformation('lydia').history.some(h=>h.action==='map'&&h.initiator==='ines'),'本人の地図を広げた行動履歴がない');
 ok($('sheet').innerHTML.includes('地図を見ながら皆に話してみる')&&state.room==='entry'&&state.visited.length===1,'地図表示だけで移動／地図から話せない');
 await submitMessage('排水室へ行こう','all');ok(state.room==='drain'&&!$('sheet').open&&actionHistory.filter(h=>h.action==='move').length===4,'地図からの会話で全員が移動しない・地図が閉じない');
 fixture();apply('lydia','light');calls=0;ok(!(await requestMap('ines','lydia_map')).performed&&calls===0&&!$('sheet').open,'イネスにない地図を本人の品として開く');
 fixture();apply('lydia','light');ask=async()=>JSON.stringify({decision:'wait',speech:'今は少し待ってもらえる？'});
 ok(!(await requestMap('lydia','lydia_map')).performed&&!state.navigation.maps.length&&!$('sheet').open,'本人が保留しても地図を共有');
 ok(state.profiles.feedback.lydia.includes('待って'),'本人の保留理由がシートに表示されない');
 ask=async()=>{throw Error('quota exceeded')};let failed=false;try{await requestMap('lydia','lydia_map')}catch{failed=true}ok(failed&&!state.navigation.maps.length,'通信失敗で地図を共有');
 ok(state.profiles.feedback.lydia.includes('利用上限'),'シートから地図を頼んだ時の接続エラーが見えない');
 ask=async()=>JSON.stringify({decision:'show',speech:'広げます。'});auditProfile=async()=>({valid:false,claims:[],conflicts:[{}]});failed=false;try{await requestMap('lydia','lydia_map')}catch{failed=true}ok(failed&&!state.navigation.maps.length,'設定不一致でも地図を共有');
 auditProfile=async()=>({valid:true,claims:[],conflicts:[]});ask=async()=>{generation++;return JSON.stringify({decision:'show',speech:'広げます。'})};ok(!(await requestMap('lydia','lydia_map')).performed&&!state.navigation.maps.length,'再開始前の地図応答を適用');
 ask=async()=>{move('hall');return JSON.stringify({decision:'show',speech:'広げます。'})};ok(!(await requestMap('lydia','lydia_map')).performed&&!state.navigation.maps.length,'移動前の地図応答を適用');
 fixture();apply('lydia','light');ask=async()=>{transferItem({item:'lydia_map',from:'lydia',to:'brom',mode:'give'});return JSON.stringify({decision:'show',speech:'広げます。'})};failed=false;try{await requestMap('lydia','lydia_map')}catch{failed=true}ok(failed&&!state.navigation.maps.length,'所持者が変わった地図を元の人が共有');
 fixture();apply('lydia','light');let discussions=0;companions=async()=>{discussions++};await submitMessage('奥へ進もう');
 ok(state.room==='entry'&&discussions===1&&!state.navigation.maps.length,'行き先の相談だけで地図を読む／移動');
 await submitMessage('下りの通路へ進もう');ok(state.room==='drain'&&state.navigation.maps.length===0,'地図なしの探索ができない');
 fixture();apply('lydia','light');ok(!(await handleNavigation({kind:'advance'})).performed&&state.phase==='explore','扉の状態を無視して戦闘へ移行');
 move('hall');state.opened=true;await submitMessage('石扉の奥へ進もう');ok(state.phase==='battle'&&state.boss===24,'開いた扉の先への会話が既存の戦闘へつながらない');
 fixture();ok(!state.navigation.maps.length&&state.navigation.known.join(',')==='entry'&&!state.navigation.offer,'再開始で地図・行き先の記憶が残る');
 return count;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 通路と地名の区別 / リディアの地図のみ / 未訪問情報の保護 / 個別所有・貸与 / 会話の相談と移動 / 本人の了承と古い応答 / 地図なし探索 / 戦闘への接続')).catch(e=>{console.error(e);process.exitCode=1});
