const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const elements={};function el(){return {value:'',textContent:'',disabled:false,open:false,isConnected:true,classList:{add(){},remove(){}},setAttribute(){},dispatchEvent(){},focus(){},showModal(){this.open=true;},close(){this.open=false;},addEventListener(){}};}
const context=vm.createContext({document:{getElementById:id=>elements[id]??=el()},window:{},el,Event:class{},crypto:require('node:crypto').webcrypto});
vm.runInContext(source.split("$('chat').onsubmit")[0],context);
vm.runInContext(`(async()=>{
 let checks=0;const ok=(v,m)=>{checks++;if(!v)throw Error(m)};
 state=initial();chat=[];state.knowledge.lydia.push('リディアだけの秘密');learnClue('lydia','darkness');state.knowledge.ines.push('自分だけの観察');
 const data=roleContext('ブロムに頼む','brom'),encoded=JSON.stringify(data);
 ok(data.actor.profile.origin.value===PROFILE_DRAFT.ines.origin,'自分の設定が欠ける');
 ok(data.recipient==='ブロム'&&encoded.includes('自分だけの観察'),'宛先や本人の観察が欠ける');
 ok(!encoded.includes('リディアだけの秘密')&&!encoded.includes(CLUES.darkness),'仲間の秘密が下書きへ漏れる');
 ok(!encoded.includes(PROFILE_DRAFT.brom.origin),'未開示の人物設定を渡す');
 ok(data.actor.inventory.every(r=>r.holder==='ines'),'他人の道具を自分の持ち物として渡す');
 ok(roleText('{"speech":"頼むわ。","action":"smash"}')==='頼むわ。','下書きの文章が読めない');
 ok(stageSpeaker('イネス（あなた）→全員','you')==='ines','話し手ではなく宛先を照らす');
 ok(stageSpeaker('ブロム（AI）','')==='brom'&&stageSpeaker('リディア','')==='lydia','仲間の発言を照らさない');
 ok(stageSpeaker('GM','gm')===null&&stageSpeaker('リディア','private')===null&&stageSpeaker('接続・応答の確認','error')===null,'GMや個人だけの記録を発言者として扱う');
 const before=JSON.stringify(state),logBefore=JSON.stringify(chat);setupRoleHelp();$('message').value='元の文';openRoleHelp();$('roleIntent').value='灯りを頼む';
 ask=async()=>'{"speech":"足元を照らしてくれる？"}';await generateRoleDraft();
 ok($('roleDraft').value==='足元を照らしてくれる？','生成した下書きが表示されない');
 ok(JSON.stringify(state)===before&&JSON.stringify(chat)===logBefore,'下書き生成だけで状態・会話を変更');
 $('roleDraft').value='ちょっと灯り、お願い！';$('roleUse').onclick();
 ok($('message').value==='ちょっと灯り、お願い！'&&!$('rolePanel').open,'自由に直した文を入力欄へ写せない');
 ok(JSON.stringify(state)===before&&JSON.stringify(chat)===logBefore,'写すだけで発言・実行');
 openRoleHelp();$('roleDraft').value='写す文';$('message').value='人間が先に直した文';$('roleUse').onclick();
 ok($('message').value==='人間が先に直した文'&&$('rolePanel').open,'編集中の元の文を上書き');
 $('roleIntent').value='お願い';let release;ask=()=>new Promise(r=>release=r);const pending=generateRoleDraft();$('roleDraft').value='自分で書いたアドリブ';release('{"speech":"後から来た下書き"}');await pending;
 ok($('roleDraft').value==='自分で書いたアドリブ','遅い応答が編集を上書き');
 const late=generateRoleDraft();$('roleClose').onclick();release('{"speech":"閉じた後の返答"}');await late;
 ok($('roleDraft').value==='自分で書いたアドリブ','閉じた後に古い応答を適用');
 openRoleHelp();$('roleIntent').value='頼む';const stale=generateRoleDraft();generation++;release('{"speech":"再開始前の返答"}');await stale;
 ok(!$('roleDraft').value,'再開始前の下書きを適用');
 openRoleHelp();$('roleIntent').value='頼む';ask=async()=>{throw Error('通信失敗')};await generateRoleDraft();
 ok(!$('roleGenerate').disabled&&$('roleStatus').textContent.includes('自分で書いて'),'通信失敗で手入力を止める');
 $('roleDraft').value='自分の言葉';$('roleUse').onclick();ok($('message').value==='自分の言葉','通信なしの自由な下書きを使えない');
 openRoleHelp('sheetMessage','lydia');$('roleDraft').value='リディア、ありがとう';$('roleUse').onclick();ok($('sheetMessage').value==='リディア、ありがとう','シートの入力へ写せない');
 const status=el(),button=el();startVoice('message',button,status);ok(status.textContent.includes('未対応')&&!voiceSession,'未対応で録音状態になる');
 let recorder;window.SpeechRecognition=class {constructor(){recorder=this;}start(){}stop(){this.stopped=true;}};
 $('message').value='こんにちは';startVoice('message',button,status);
 ok(voiceSession&&recorder.lang==='ja-JP'&&!recorder.continuous,'常時音声入力になる');
 const result=[{0:{transcript:'ブロム、頼んだわ'},isFinal:true}];recorder.onresult({results:result});
 ok($('message').value==='こんにちは ブロム、頼んだわ','聞き取った文を編集欄へ入れない');
 ok(JSON.stringify(state)===before&&JSON.stringify(chat)===logBefore,'音声結果が自動でゲームへ送信');
 stopVoice();ok(recorder.stopped&&!voiceSession,'停止できない');
 $('message').value='';startVoice('message',button,status);$('message').value='入力中';recorder.onresult({results:result});ok($('message').value==='入力中','認識結果が手入力を上書き');
 stopVoice();$('message').value='';startVoice('message',button,status);generation++;recorder.onresult({results:result});ok(!$('message').value,'再開始後に古い音声を入れる');stopVoice();
 return checks;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 本人の設定と知識 / 仲間の秘密保護 / 編集と任意の下書き / 非送信・非実行 / 遅い応答・再開始・通信失敗 / シート入力 / マイクの開始・停止・手入力保護 / 照明の話し手と宛先・非公開記録の区別')).catch(e=>{console.error(e);process.exitCode=1});
