const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/game.js','utf8');
const elements={};
const element=()=>({children:[],append(...nodes){this.children.push(...nodes)},scrollHeight:0,clientHeight:0,scrollTop:0});
const context=vm.createContext({document:{getElementById(id){return elements[id]??=element()},createElement:element,createTextNode:text=>({textContent:text})},crypto:require('node:crypto').webcrypto});
vm.runInContext(source,context,{filename:__dirname+'/game.js'});
vm.runInContext(`(async()=>{
 let count=0;const ok=(v,m)=>{count++;if(!v)throw Error(m)};
 state=initial();chat=[];actionHistory=[];humanRequests=[];explorationOffers={};
 ok(!targetPortrait('etching')&&!targetPortrait('cache'),'未発見の地点の寄り絵を先に表示');
 state.lit=true;state.everLit=true;const before=JSON.stringify(state);
 ok(targetPortrait('cart').includes('cart-v1.png'),'発見済み台車の寄り絵がない');
 ok(JSON.stringify(state)===before,'寄り絵を開くだけで調査状態を変更');
 ok(!targetPortrait('wheel')&&!targetPortrait('../secret'),'別シーンや未知の地点の画像を表示');
 state.discovery.cache=true;state.discovery.opened=true;
 ok(targetPortrait('cache').includes('最初に見えた外観'),'変化前の絵を現在の外観と誤表示');
 state=initial();

 ok(!sheetItemView('brom','hammer')&&!sheetItemView('lydia','staff'),'未開示の所持品の画像を先に表示');
 revealProfile('brom',[{key:'item0'}]);const inventoryBefore=JSON.stringify(state);
 ok(sheetItemView('brom','hammer').detail==='詳しい用途はまだ聞いていない','品名だけ既知なのに用途を開示');
 ok(sheetItemView('ines','rope').detail===ITEM_DEFS.rope.detail,'自分の品の用途を隠す');
 ok(JSON.stringify(state)===inventoryBefore,'画像閲覧で所有・知識を変更');
 ok(!sheetItemView('gareth','hammer')&&!sheetItemView('ines','ines_map')&&!sheetItemView('ines','../secret'),'別人の品や地図・未知の画像を開く');
 transferItem({item:'hammer',from:'brom',to:'ines',mode:'lend'});
 ok(sheetItemView('ines','hammer').holder==='ines'&&sheetItemView('brom','hammer').owner==='brom','貸与後の所持・所有の表示が不正');
 transferItem({item:'hammer',from:'ines',to:'brom',mode:'return'});
 transferItem({item:'hammer',from:'brom',to:'gareth',mode:'give'});
 ok(!sheetItemView('ines','hammer'),'所持も所有も失った品の画像を残す');
 state=initial();actionHistory=[];
 state.knowledge.brom.push('他人だけの秘密');ok(privateSummary().count===0,'他人の秘密を発見カードへ表示');
 state.knowledge.ines.push('古い跡','古い跡','別の痕跡');ok(privateSummary().count===2&&privateSummary().latest==='別の痕跡','重複した発見を数えるか最新が異なる');
 ok(!privateSummary().clue,'普通の観察を共有済みの手がかりへ勝手に変換');
 publishReport('ines','別の痕跡');ok(privateSummary().count===1&&privateSummary().latest==='古い跡','共有済みを未共有と表示');
 learnClue('ines','etching');ok(privateSummary().clue==='etching','自分の未共有の手がかりを共有できない');
 shareClue('ines','etching');ok(privateSummary().count===1&&!privateSummary().clue,'共有後も同じ手がかりを未共有と表示');
 publishReport('ines','古い跡');ok(privateSummary().count===0&&!privateSummary().latest,'全部共有した後に古い発見カードを残す');
 state=initial();state.lit=true;state.everLit=true;explorationOffers.brom={room:'entry',action:'inspect_cart'};
 ok(conversationStatus().some(t=>t.includes('ブロムの申し出')&&t.includes('台車')),'申し出を実行結果と区別できない');
 ok(!state.seen.brom&&actionHistory.length===0,'申し出を表示しただけで実行');
 state.room='hall';ok(!conversationStatus().some(t=>t.includes('台車')),'前の場所の申し出を表示');
 state.room='entry';state.seen.brom=['cart'];publishReport('brom',inspectText('brom','cart',state));ok(!conversationStatus().some(t=>t.includes('台車')),'済んだ一般調査を返事待ちとして表示');
 state=initial();state.lit=true;state.everLit=true;explorationOffers={};apply('brom','inspect_cart');publishReport('brom',inspectText('brom','cart',state));askHuman=()=>{};
 humanRequests=[{id:'brom',action:'take',room:'entry',epoch:generation,paused:true}];ok(conversationStatus().some(t=>t.includes('保留中')),'人間が保留した依頼の表示が異なる');
 state.phase='battle';ok(conversationStatus().length===0,'戦闘へ探索の申し出を表示');state.phase='explore';
 pendingTransfer={epoch:generation-1};ok(!conversationStatus().some(t=>t.includes('受け渡し')),'再開始前の受け渡しを表示');
 pendingTransfer={epoch:generation};ok(conversationStatus().some(t=>t.includes('受け渡し')),'現在の受け渡し確認を隠す');pendingTransfer=null;
 state=initial();chat=[];speakGM=()=>{};say('ブロム','輪を支えようか？');sayResult('GM','ブロムが輪を支えた。');
 ok(chat[0].kind===''&&chat[1].kind==='gm'&&Object.keys(chat[1]).join()==='who,text,kind','UIタグがAIの会話記録の形式を変更');
 const log=$('log');ok(!log.children[0].className.includes('result')&&log.children[1].className.includes('result'),'申し出と実結果に同じタグを表示');
 ok(log.children[1].children[0].children[0].textContent==='実行結果','実結果の表示タグがない');
 render=()=>{};companions=async()=>{};run=async fn=>fn();state=initial();learnClue('ines','etching');chat=[];busy=true;
 publishOwnClue('etching');ok(!state.discovery.shared.length&&!chat.length,'処理中に秘密を二重送信');busy=false;
 await publishOwnClue('cache_lock');ok(!state.discovery.shared.length,'知らない手がかりを共有');
 await publishOwnClue('etching');ok(state.discovery.shared.includes('etching')&&chat.length===1&&chat[0].kind==='you','本人の操作による既知情報の共有ができない');
 state=initial();chat=[];state.knowledge.ines.push('軸に鉄片');busy=true;publishOwnKnowledge(0);ok(privateSummary().count===1&&!chat.length,'処理中に発見を二重送信');busy=false;
 await publishOwnKnowledge(5);ok(privateSummary().count===1&&!chat.length,'存在しない発見を共有');
 await publishOwnKnowledge(0);ok(privateSummary().count===0&&chat.length===1&&chat[0].kind==='you','手がかりでない自分の発見を共有できない');
 await publishOwnKnowledge(0);ok(chat.length===1,'共有済みの発見を二重送信');
 return count;
})()`,context).then(n=>console.log('PASS: '+n+' checks — 発見の重複整理・本人限定 / 未共有と共有済み / 現在の申し出・保留 / 古い申し出の除外 / 実結果の表示と会話形式維持 / 本人の情報共有 / 寄り絵の発見条件・状態保護 / 持ち物の画像・用途開示・所有追従')).catch(e=>{console.error(e);process.exitCode=1});
