const {chromium}=require('/Users/yasuda_k/Desktop/Terminus/trpg-gm-mock2/node_modules/playwright');
const OUT='/Users/yasuda_k/Desktop/Terminus/trpg-gm-mock3/prototype/art-preview/gareth-visibility-study/';
(async()=>{const b=await chromium.launch();const errors=[];
 const page=await b.newPage({viewport:{width:1440,height:900}});page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text())});page.on('pageerror',e=>errors.push(String(e)));
 const glb=[];page.on('response',r=>{if(r.url().includes('/standees/gareth'))glb.push(r.status()+' '+r.url().split('/prototype/')[1]);});
 await page.goto('http://127.0.0.1:8797/prototype/index.html');await page.waitForFunction(()=>typeof state!=='undefined'&&document.querySelector('#scene.stage-ready'));await page.waitForTimeout(1500);
 const say=async t=>{const n0=await page.evaluate(()=>chat.length);await page.fill('#message',t);await page.press('#message','Enter');await page.waitForFunction(n=>!busy&&chat.length>n,n0,{timeout:120000});await page.waitForTimeout(1000);return page.evaluate(n=>chat.slice(n).map(c=>c.who+'｜'+c.text),n0);};
 const log={};
 log.equipChat=await say('ガレス、片手剣を腰に下げておいて');
 log.lightChat=await say('マレン、ランタンを点けて');
 await page.waitForFunction(()=>($('scene').dataset.stageVariants||'').includes('gareth:gareth-sheathed-visible'),null,{timeout:30000}).catch(()=>{});
 await page.waitForTimeout(3500);
 const r=await page.evaluate(()=>{const s=$('scene').getBoundingClientRect();const rects=stageView.actorRects();const labels=[...document.querySelectorAll('#points [data-target]')].filter(b=>!b.hidden).map(b=>{const q=b.getBoundingClientRect();return {t:b.dataset.target,text:b.textContent,x:q.x-s.x,y:q.y-s.y,w:q.width,h:q.height}});
  const hit=(a,c)=>a.x<c.x+c.width&&c.x<a.x+a.w&&a.y<c.y+c.height&&c.y<a.y+a.h;
  return {dagger:state.items.dagger,lit:state.lit,gareth:scenarioStandeeVariant(stageSnapshot().actors.find(a=>a.id==='gareth')),variants:$('scene').dataset.stageVariants,missing:$('scene').dataset.stageEquipmentMissing||'',assetError:$('scene').dataset.stageAssetError||'',actorRects:rects,labels,overlaps:labels.flatMap(l=>rects.filter(a=>hit(l,a)).map(a=>l.text+'×'+(a.id||'?'))),scene:[s.x,s.y,s.width,s.height]};});
 Object.assign(log,r,{glbResponses:glb,errors});
 await page.screenshot({path:OUT+'browser-equipped-lit.png',clip:{x:r.scene[0],y:r.scene[1],width:r.scene[2],height:r.scene[3]}});
 await page.screenshot({path:OUT+'browser-equipped-lit-full.png'});
 console.log(JSON.stringify(log,null,1));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
